#nullable enable

namespace Cafe.Launcher.Avalonia.Resources;

using System.Globalization;
using System.Resources;

/// <summary>
/// Strongly typed accessors for <c>LauncherStrings.resx</c>.
/// Generated by scripts/Generate-LauncherStringsDesigner.ps1; do not edit by hand.
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("scripts/Generate-LauncherStringsDesigner.ps1", "1.0.0.0")]
[System.Diagnostics.DebuggerNonUserCodeAttribute]
internal static class LauncherStrings
{
    private static ResourceManager? resourceMan;

    public static ResourceManager ResourceManager =>
        resourceMan ??= new ResourceManager(
            "Cafe.Launcher.Avalonia.Resources.LauncherStrings",
            typeof(LauncherStrings).Assembly);

    private static string GetRequiredString(string key) =>
        ResourceManager.GetString(key, CultureInfo.CurrentUICulture)
        ?? throw new MissingManifestResourceException($"Resource key '{key}' was not found.");

    public static string AboutCopyrightText => GetRequiredString("aboutCopyrightText");

    public static string AboutDescription => GetRequiredString("aboutDescription");

    public static string AboutDisclaimerText => GetRequiredString("aboutDisclaimerText");

    public static string AboutLinks => GetRequiredString("aboutLinks");

    public static string AboutQuickLinks => GetRequiredString("aboutQuickLinks");

    public static string AboutRowAvalonia => GetRequiredString("aboutRowAvalonia");

    public static string AboutRowBuildConfig => GetRequiredString("aboutRowBuildConfig");

    public static string AboutRowCommit => GetRequiredString("aboutRowCommit");

    public static string AboutRowPlatform => GetRequiredString("aboutRowPlatform");

    public static string AboutRowRuntime => GetRequiredString("aboutRowRuntime");

    public static string AboutVersionCaption => GetRequiredString("aboutVersionCaption");

    public static string AppearancePreviewFailed => GetRequiredString("appearancePreviewFailed");

    public static string BackgroundFillColor => GetRequiredString("backgroundFillColor");

    public static string BackgroundFillColorDescription => GetRequiredString("backgroundFillColorDescription");

    public static string BackgroundFit => GetRequiredString("backgroundFit");

    public static string BackgroundFitDescription => GetRequiredString("backgroundFitDescription");

    public static string BackgroundFitFill => GetRequiredString("backgroundFitFill");

    public static string BackgroundFitUniform => GetRequiredString("backgroundFitUniform");

    public static string BackgroundFitUniformToFill => GetRequiredString("backgroundFitUniformToFill");

    public static string BackgroundSource => GetRequiredString("backgroundSource");

    public static string BackgroundSourceBundled => GetRequiredString("backgroundSourceBundled");

    public static string BackgroundSourceCustom => GetRequiredString("backgroundSourceCustom");

    public static string BackgroundSourceDescription => GetRequiredString("backgroundSourceDescription");

    public static string BackgroundSourceRemote => GetRequiredString("backgroundSourceRemote");

    public static string Banner => GetRequiredString("banner");

    public static string BannerLoading => GetRequiredString("bannerLoading");

    public static string BannerLoadingFailed => GetRequiredString("bannerLoadingFailed");

    public static string BuildingFileList => GetRequiredString("buildingFileList");

    public static string Cancel => GetRequiredString("cancel");

    public static string CarouselPage => GetRequiredString("carouselPage");

    public static string CdnConfigIncomplete => GetRequiredString("cdnConfigIncomplete");

    public static string ChangePath => GetRequiredString("changePath");

    public static string CheckUpdates => GetRequiredString("checkUpdates");

    public static string Choose => GetRequiredString("choose");

    public static string ChooseBackgroundFolderTitle => GetRequiredString("chooseBackgroundFolderTitle");

    public static string ChooseBackgroundImageTitle => GetRequiredString("chooseBackgroundImageTitle");

    public static string ChooseFolder => GetRequiredString("chooseFolder");

    public static string ChooseImage => GetRequiredString("chooseImage");

    public static string ChooseInstallFolder => GetRequiredString("chooseInstallFolder");

    public static string ClearBackground => GetRequiredString("clearBackground");

    public static string Close => GetRequiredString("close");

    public static string CloseBehavior => GetRequiredString("closeBehavior");

    public static string CloseBehaviorDescription => GetRequiredString("closeBehaviorDescription");

    public static string CloseBehaviorExit => GetRequiredString("closeBehaviorExit");

    public static string CloseBehaviorMinimize => GetRequiredString("closeBehaviorMinimize");

    public static string CloseDownloadMessage => GetRequiredString("closeDownloadMessage");

    public static string CloseDownloadTitle => GetRequiredString("closeDownloadTitle");

    public static string ConfirmUninstall => GetRequiredString("confirmUninstall");

    public static string ContactCustomerSupport => GetRequiredString("contactCustomerSupport");

    public static string ContinueDownload => GetRequiredString("continueDownload");

    public static string CrashWindowBuild => GetRequiredString("crashWindowBuild");

    public static string CrashWindowCaption => GetRequiredString("crashWindowCaption");

    public static string CrashWindowCopied => GetRequiredString("crashWindowCopied");

    public static string CrashWindowCopyDetails => GetRequiredString("crashWindowCopyDetails");

    public static string CrashWindowDescription => GetRequiredString("crashWindowDescription");

    public static string CrashWindowExit => GetRequiredString("crashWindowExit");

    public static string CrashWindowOpenLogs => GetRequiredString("crashWindowOpenLogs");

    public static string CrashWindowReportId => GetRequiredString("crashWindowReportId");

    public static string CrashWindowStatus => GetRequiredString("crashWindowStatus");

    public static string CrashWindowTechnicalDetails => GetRequiredString("crashWindowTechnicalDetails");

    public static string CrashWindowTime => GetRequiredString("crashWindowTime");

    public static string CrashWindowTitle => GetRequiredString("crashWindowTitle");

    public static string CrashWindowVersion => GetRequiredString("crashWindowVersion");

    public static string CustomBackground => GetRequiredString("customBackground");

    public static string CustomBackgroundDescription => GetRequiredString("customBackgroundDescription");

    public static string DebugActionFailureMessage => GetRequiredString("debugActionFailureMessage");

    public static string DebugActionFailureTitle => GetRequiredString("debugActionFailureTitle");

    public static string DebugActionToastMessage => GetRequiredString("debugActionToastMessage");

    public static string DebugActionToastTitle => GetRequiredString("debugActionToastTitle");

    public static string DebugCriticalErrorMessage => GetRequiredString("debugCriticalErrorMessage");

    public static string DebugCriticalErrorTriggered => GetRequiredString("debugCriticalErrorTriggered");

    public static string DebugFatalCrashTriggered => GetRequiredString("debugFatalCrashTriggered");

    public static string DebugGameOperations => GetRequiredString("debugGameOperations");

    public static string DebugHandledErrorMessage => GetRequiredString("debugHandledErrorMessage");

    public static string DebugHandledErrorSimulated => GetRequiredString("debugHandledErrorSimulated");

    public static string DebugIdle => GetRequiredString("debugIdle");

    public static string DebugLogEntryWritten => GetRequiredString("debugLogEntryWritten");

    public static string DebugLogLevelSet => GetRequiredString("debugLogLevelSet");

    public static string DebugOutput => GetRequiredString("debugOutput");

    public static string DebugPanel => GetRequiredString("debugPanel");

    public static string DebugPauseResume => GetRequiredString("debugPauseResume");

    public static string DebugResetSettingsConfirm => GetRequiredString("debugResetSettingsConfirm");

    public static string DebugResetSettingsDescription => GetRequiredString("debugResetSettingsDescription");

    public static string DebugResetSettingsTitle => GetRequiredString("debugResetSettingsTitle");

    public static string DebugSettingsReadFailed => GetRequiredString("debugSettingsReadFailed");

    public static string DebugSettingsReset => GetRequiredString("debugSettingsReset");

    public static string DebugSimulateError => GetRequiredString("debugSimulateError");

    public static string DebugSimulateFailure => GetRequiredString("debugSimulateFailure");

    public static string DebugSimulateFatalCrash => GetRequiredString("debugSimulateFatalCrash");

    public static string DebugSimulateFatalCrashMessage => GetRequiredString("debugSimulateFatalCrashMessage");

    public static string DebugSimulateSuccess => GetRequiredString("debugSimulateSuccess");

    public static string DebugSimulateUnhandledCrash => GetRequiredString("debugSimulateUnhandledCrash");

    public static string DebugSimulateUnhandledCrashMessage => GetRequiredString("debugSimulateUnhandledCrashMessage");

    public static string DebugStateRefreshTriggered => GetRequiredString("debugStateRefreshTriggered");

    public static string DebugStatus => GetRequiredString("debugStatus");

    public static string DebugSystemInfo => GetRequiredString("debugSystemInfo");

    public static string DebugSystemInfoFormat => GetRequiredString("debugSystemInfoFormat");

    public static string DebugTestActionToast => GetRequiredString("debugTestActionToast");

    public static string DebugTestErrorToast => GetRequiredString("debugTestErrorToast");

    public static string DebugTestInfoToast => GetRequiredString("debugTestInfoToast");

    public static string DebugTestLogMessage => GetRequiredString("debugTestLogMessage");

    public static string DebugTestSuccessToast => GetRequiredString("debugTestSuccessToast");

    public static string DebugTestToastMessage => GetRequiredString("debugTestToastMessage");

    public static string DebugTestWarningToast => GetRequiredString("debugTestWarningToast");

    public static string DebugToastShown => GetRequiredString("debugToastShown");

    public static string DefaultBackgroundArtwork => GetRequiredString("defaultBackgroundArtwork");

    public static string DefaultBackgroundCopyrightText => GetRequiredString("defaultBackgroundCopyrightText");

    public static string DesignGalleryHint => GetRequiredString("designGalleryHint");

    public static string DesignGalleryTitle => GetRequiredString("designGalleryTitle");

    public static string DesignGroupBorder => GetRequiredString("designGroupBorder");

    public static string DesignGroupColor => GetRequiredString("designGroupColor");

    public static string DesignGroupComponent => GetRequiredString("designGroupComponent");

    public static string DesignGroupControl => GetRequiredString("designGroupControl");

    public static string DesignGroupElevation => GetRequiredString("designGroupElevation");

    public static string DesignGroupIcon => GetRequiredString("designGroupIcon");

    public static string DesignGroupLayout => GetRequiredString("designGroupLayout");

    public static string DesignGroupMotion => GetRequiredString("designGroupMotion");

    public static string DesignGroupOther => GetRequiredString("designGroupOther");

    public static string DesignGroupRadius => GetRequiredString("designGroupRadius");

    public static string DesignGroupSpacing => GetRequiredString("designGroupSpacing");

    public static string DesignGroupStateLayer => GetRequiredString("designGroupStateLayer");

    public static string DesignGroupText => GetRequiredString("designGroupText");

    public static string DesignGroupTypography => GetRequiredString("designGroupTypography");

    public static string DesignMatrixCardWithToast => GetRequiredString("designMatrixCardWithToast");

    public static string DesignMatrixErrorButton => GetRequiredString("designMatrixErrorButton");

    public static string DesignMatrixFilledButton => GetRequiredString("designMatrixFilledButton");

    public static string DesignMatrixOutlinedButton => GetRequiredString("designMatrixOutlinedButton");

    public static string DesignMatrixSettingsRow => GetRequiredString("designMatrixSettingsRow");

    public static string DesignMatrixTextButton => GetRequiredString("designMatrixTextButton");

    public static string DesignStateDisabled => GetRequiredString("designStateDisabled");

    public static string DesignStateFocus => GetRequiredString("designStateFocus");

    public static string DesignStateHover => GetRequiredString("designStateHover");

    public static string DesignStateInvalid => GetRequiredString("designStateInvalid");

    public static string DesignStateNormal => GetRequiredString("designStateNormal");

    public static string DesignStatePressed => GetRequiredString("designStatePressed");

    public static string DiscardChanges => GetRequiredString("discardChanges");

    public static string DiskSpace => GetRequiredString("diskSpace");

    public static string DiskSpaceCheck => GetRequiredString("diskSpaceCheck");

    public static string DiskSpaceEmpty => GetRequiredString("diskSpaceEmpty");

    public static string DiskSpaceInsufficient => GetRequiredString("diskSpaceInsufficient");

    public static string DiskSpaceInsufficientDetail => GetRequiredString("diskSpaceInsufficientDetail");

    public static string DiskSpaceOkSuffix => GetRequiredString("diskSpaceOkSuffix");

    public static string DiskSpaceShortSuffix => GetRequiredString("diskSpaceShortSuffix");

    public static string Downloading => GetRequiredString("downloading");

    public static string DownloadRemoteConfigIncomplete => GetRequiredString("downloadRemoteConfigIncomplete");

    public static string DownloadSource => GetRequiredString("downloadSource");

    public static string DownloadSourceCafe => GetRequiredString("downloadSourceCafe");

    public static string DownloadSourceChangedRepairPrompt => GetRequiredString("downloadSourceChangedRepairPrompt");

    public static string DownloadSourceDescription => GetRequiredString("downloadSourceDescription");

    public static string DownloadSourceLoading => GetRequiredString("downloadSourceLoading");

    public static string DownloadSourceOfficial => GetRequiredString("downloadSourceOfficial");

    public static string DownloadSourceValue => GetRequiredString("downloadSourceValue");

    public static string DownloadSpeedLimit => GetRequiredString("downloadSpeedLimit");

    public static string DownloadSpeedLimitDescription => GetRequiredString("downloadSpeedLimitDescription");

    public static string EnableHttp2 => GetRequiredString("enableHttp2");

    public static string EnableHttp2Description => GetRequiredString("enableHttp2Description");

    public static string EnableStartupUpdateCheck => GetRequiredString("enableStartupUpdateCheck");

    public static string EnableStartupUpdateCheckDescription => GetRequiredString("enableStartupUpdateCheckDescription");

    public static string ErrorDialogContinue => GetRequiredString("errorDialogContinue");

    public static string ErrorDialogCopyDetails => GetRequiredString("errorDialogCopyDetails");

    public static string ErrorDialogDescription => GetRequiredString("errorDialogDescription");

    public static string ErrorDialogTitle => GetRequiredString("errorDialogTitle");

    public static string ErrorDialogViewLog => GetRequiredString("errorDialogViewLog");

    public static string ErrorFakeIpDns => GetRequiredString("errorFakeIpDns");

    public static string ErrorNetworkUnavailable => GetRequiredString("errorNetworkUnavailable");

    public static string EstimatedTimeRemaining => GetRequiredString("estimatedTimeRemaining");

    public static string Executable => GetRequiredString("executable");

    public static string ExecutableLoading => GetRequiredString("executableLoading");

    public static string ExecutableNameValue => GetRequiredString("executableNameValue");

    public static string ExecutableValue => GetRequiredString("executableValue");

    public static string ExitLauncher => GetRequiredString("exitLauncher");

    public static string ExportLogs => GetRequiredString("exportLogs");

    public static string FileAccessDenied => GetRequiredString("fileAccessDenied");

    public static string FileOperationFailed => GetRequiredString("fileOperationFailed");

    public static string GameAlreadyCurrent => GetRequiredString("gameAlreadyCurrent");

    public static string GameBelowLowestVersion => GetRequiredString("gameBelowLowestVersion");

    public static string GameCheckUpdate => GetRequiredString("gameCheckUpdate");

    public static string GameCheckUpdateAvailable => GetRequiredString("gameCheckUpdateAvailable");

    public static string GameCheckUpdateFailed => GetRequiredString("gameCheckUpdateFailed");

    public static string GameCheckUpdateUpToDate => GetRequiredString("gameCheckUpdateUpToDate");

    public static string GameConfigMetadataMissing => GetRequiredString("gameConfigMetadataMissing");

    public static string GameCorruptedInstallationState => GetRequiredString("gameCorruptedInstallationState");

    public static string GameCreateShortcut => GetRequiredString("gameCreateShortcut");

    public static string GameDirectoryNameInvalid => GetRequiredString("gameDirectoryNameInvalid");

    public static string GameDisplayName => GetRequiredString("gameDisplayName");

    public static string GameExecutableMissing => GetRequiredString("gameExecutableMissing");

    public static string GameExecutableNameEmpty => GetRequiredString("gameExecutableNameEmpty");

    public static string GameExecutableNameInvalid => GetRequiredString("gameExecutableNameInvalid");

    public static string GameExecutableRunning => GetRequiredString("gameExecutableRunning");

    public static string GameFolderMissing => GetRequiredString("gameFolderMissing");

    public static string GameInstallationStateReadFailed => GetRequiredString("gameInstallationStateReadFailed");

    public static string GameInstallOrUpdateFailed => GetRequiredString("gameInstallOrUpdateFailed");

    public static string GameInstallPathNotConfigured => GetRequiredString("gameInstallPathNotConfigured");

    public static string GameIsRunning => GetRequiredString("gameIsRunning");

    public static string GameLaunched => GetRequiredString("gameLaunched");

    public static string GameLaunchedExiting => GetRequiredString("gameLaunchedExiting");

    public static string GameLaunchedMinimized => GetRequiredString("gameLaunchedMinimized");

    public static string GameLaunchFailed => GetRequiredString("gameLaunchFailed");

    public static string GameManagement => GetRequiredString("gameManagement");

    public static string GameManagementDescription => GetRequiredString("gameManagementDescription");

    public static string GameNotInstalled => GetRequiredString("gameNotInstalled");

    public static string GameOpenFolder => GetRequiredString("gameOpenFolder");

    public static string GamePath => GetRequiredString("gamePath");

    public static string GamePathMissing => GetRequiredString("gamePathMissing");

    public static string GamePathProtected => GetRequiredString("gamePathProtected");

    public static string GamePathUpdated => GetRequiredString("gamePathUpdated");

    public static string GamePathUpdateFailed => GetRequiredString("gamePathUpdateFailed");

    public static string GameProcessScanUnavailable => GetRequiredString("gameProcessScanUnavailable");

    public static string GameProcessStarted => GetRequiredString("gameProcessStarted");

    public static string GameRemoteStateUnavailable => GetRequiredString("gameRemoteStateUnavailable");

    public static string GameRepairFailed => GetRequiredString("gameRepairFailed");

    public static string GameRuntimeEnvironmentMountNoExec => GetRequiredString("gameRuntimeEnvironmentMountNoExec");

    public static string GameRuntimeEnvironmentPrefixNotWritable => GetRequiredString("gameRuntimeEnvironmentPrefixNotWritable");

    public static string GameRuntimeEnvironmentSymlinksUnsupported => GetRequiredString("gameRuntimeEnvironmentSymlinksUnsupported");

    public static string GameRuntimeNoRunnerAvailable => GetRequiredString("gameRuntimeNoRunnerAvailable");

    public static string GameRuntimePrefixPath => GetRequiredString("gameRuntimePrefixPath");

    public static string GameRuntimePrefixPathDescription => GetRequiredString("gameRuntimePrefixPathDescription");

    public static string GameRuntimePrefixPathPlaceholder => GetRequiredString("gameRuntimePrefixPathPlaceholder");

    public static string GameRuntimeProtonPath => GetRequiredString("gameRuntimeProtonPath");

    public static string GameRuntimeProtonPathDescription => GetRequiredString("gameRuntimeProtonPathDescription");

    public static string GameRuntimeProtonPathPlaceholder => GetRequiredString("gameRuntimeProtonPathPlaceholder");

    public static string GameRuntimeRunner => GetRequiredString("gameRuntimeRunner");

    public static string GameRuntimeRunnerAuto => GetRequiredString("gameRuntimeRunnerAuto");

    public static string GameRuntimeRunnerDescription => GetRequiredString("gameRuntimeRunnerDescription");

    public static string GameRuntimeRunnerNative => GetRequiredString("gameRuntimeRunnerNative");

    public static string GameRuntimeRunnerPath => GetRequiredString("gameRuntimeRunnerPath");

    public static string GameRuntimeRunnerPathDescription => GetRequiredString("gameRuntimeRunnerPathDescription");

    public static string GameRuntimeRunnerPathPlaceholder => GetRequiredString("gameRuntimeRunnerPathPlaceholder");

    public static string GameRuntimeRunnerUmu => GetRequiredString("gameRuntimeRunnerUmu");

    public static string GameRuntimeRunnerWine => GetRequiredString("gameRuntimeRunnerWine");

    public static string GameRuntimeStatusAvailable => GetRequiredString("gameRuntimeStatusAvailable");

    public static string GameRuntimeStatusBroken => GetRequiredString("gameRuntimeStatusBroken");

    public static string GameRuntimeStatusChecking => GetRequiredString("gameRuntimeStatusChecking");

    public static string GameRuntimeStatusDetailFormat => GetRequiredString("gameRuntimeStatusDetailFormat");

    public static string GameRuntimeStatusEntryDetailFormat => GetRequiredString("gameRuntimeStatusEntryDetailFormat");

    public static string GameRuntimeStatusEntryFormat => GetRequiredString("gameRuntimeStatusEntryFormat");

    public static string GameRuntimeStatusNotFound => GetRequiredString("gameRuntimeStatusNotFound");

    public static string GameRuntimeStatusTitle => GetRequiredString("gameRuntimeStatusTitle");

    public static string GameRuntimeStatusUnsupported => GetRequiredString("gameRuntimeStatusUnsupported");

    public static string GameSessionExited => GetRequiredString("gameSessionExited");

    public static string GameSessionExitedNoCode => GetRequiredString("gameSessionExitedNoCode");

    public static string GameSessionRunning => GetRequiredString("gameSessionRunning");

    public static string GameSessionStartFailed => GetRequiredString("gameSessionStartFailed");

    public static string GameSessionStarting => GetRequiredString("gameSessionStarting");

    public static string GameShortcutCreated => GetRequiredString("gameShortcutCreated");

    public static string GameShortcutFailed => GetRequiredString("gameShortcutFailed");

    public static string GameShortcutTargetMissing => GetRequiredString("gameShortcutTargetMissing");

    public static string GameShortcutUnsupported => GetRequiredString("gameShortcutUnsupported");

    public static string GitHubReleaseRepository => GetRequiredString("gitHubReleaseRepository");

    public static string GitHubRepository => GetRequiredString("gitHubRepository");

    public static string HelpDocs => GetRequiredString("helpDocs");

    public static string InstallGame => GetRequiredString("installGame");

    public static string InstallUpdateCompleted => GetRequiredString("installUpdateCompleted");

    public static string InstallUpdateFailedTitle => GetRequiredString("installUpdateFailedTitle");

    public static string IssueTracker => GetRequiredString("issueTracker");

    public static string KeepEditing => GetRequiredString("keepEditing");

    public static string Language => GetRequiredString("language");

    public static string LanguageAuto => GetRequiredString("languageAuto");

    public static string LanguageDescription => GetRequiredString("languageDescription");

    public static string LaunchBehavior => GetRequiredString("launchBehavior");

    public static string LaunchBehaviorDescription => GetRequiredString("launchBehaviorDescription");

    public static string LaunchBehaviorKeepOpen => GetRequiredString("launchBehaviorKeepOpen");

    public static string LaunchCheck => GetRequiredString("launchCheck");

    public static string LaunchCheckDescription => GetRequiredString("launchCheckDescription");

    public static string LaunchCheckLoading => GetRequiredString("launchCheckLoading");

    public static string LaunchCheckLocalManifest => GetRequiredString("launchCheckLocalManifest");

    public static string LaunchCheckNone => GetRequiredString("launchCheckNone");

    public static string LaunchCheckRemoteManifest => GetRequiredString("launchCheckRemoteManifest");

    public static string LaunchCheckRemoteUnavailable => GetRequiredString("launchCheckRemoteUnavailable");

    public static string LaunchCheckSkipped => GetRequiredString("launchCheckSkipped");

    public static string LaunchCheckWithMessage => GetRequiredString("launchCheckWithMessage");

    public static string LaunchDamageRepairPrompt => GetRequiredString("launchDamageRepairPrompt");

    public static string LauncherCoreRefreshFailed => GetRequiredString("launcherCoreRefreshFailed");

    public static string LauncherInitFailed => GetRequiredString("launcherInitFailed");

    public static string LauncherLoadingValue => GetRequiredString("launcherLoadingValue");

    public static string LauncherStateNotLoaded => GetRequiredString("launcherStateNotLoaded");

    public static string LauncherUpdateApplyFailed => GetRequiredString("launcherUpdateApplyFailed");

    public static string LauncherUpdateAvailableMessage => GetRequiredString("launcherUpdateAvailableMessage");

    public static string LauncherUpdateAvailableTitle => GetRequiredString("launcherUpdateAvailableTitle");

    public static string LauncherUpdateChannel => GetRequiredString("launcherUpdateChannel");

    public static string LauncherUpdateChannelBeta => GetRequiredString("launcherUpdateChannelBeta");

    public static string LauncherUpdateChannelDescription => GetRequiredString("launcherUpdateChannelDescription");

    public static string LauncherUpdateChannelStable => GetRequiredString("launcherUpdateChannelStable");

    public static string LauncherUpdateCheckFailed => GetRequiredString("launcherUpdateCheckFailed");

    public static string LauncherUpdateDownload => GetRequiredString("launcherUpdateDownload");

    public static string LauncherUpdateDownloadFailed => GetRequiredString("launcherUpdateDownloadFailed");

    public static string LauncherUpdateDownloading => GetRequiredString("launcherUpdateDownloading");

    public static string LauncherUpdateFileSize => GetRequiredString("launcherUpdateFileSize");

    public static string LauncherUpdateInAppUnavailableHelper => GetRequiredString("launcherUpdateInAppUnavailableHelper");

    public static string LauncherUpdateInAppUnavailablePackage => GetRequiredString("launcherUpdateInAppUnavailablePackage");

    public static string LauncherUpdateInAppUnavailablePlatform => GetRequiredString("launcherUpdateInAppUnavailablePlatform");

    public static string LauncherUpdateLater => GetRequiredString("launcherUpdateLater");

    public static string LauncherUpdateOpenReleasePage => GetRequiredString("launcherUpdateOpenReleasePage");

    public static string LauncherUpdateReadyToRestart => GetRequiredString("launcherUpdateReadyToRestart");

    public static string LauncherUpdateRestart => GetRequiredString("launcherUpdateRestart");

    public static string LauncherUpdateUpToDate => GetRequiredString("launcherUpdateUpToDate");

    public static string LauncherUpdateView => GetRequiredString("launcherUpdateView");

    public static string LauncherVersionLabel => GetRequiredString("launcherVersionLabel");

    public static string LocalManifestMetadataMissing => GetRequiredString("localManifestMetadataMissing");

    public static string LocalManifestMissing => GetRequiredString("localManifestMissing");

    public static string LocalManifestUnreadable => GetRequiredString("localManifestUnreadable");

    public static string LogExportConfirm => GetRequiredString("logExportConfirm");

    public static string LogExportContentGroup => GetRequiredString("logExportContentGroup");

    public static string LogExportFailed => GetRequiredString("logExportFailed");

    public static string LogExportFolderPickerTitle => GetRequiredString("logExportFolderPickerTitle");

    public static string LogExportIncludeCrashReports => GetRequiredString("logExportIncludeCrashReports");

    public static string LogExportIncludeCrashReportsDescription => GetRequiredString("logExportIncludeCrashReportsDescription");

    public static string LogExportIncludeLogs => GetRequiredString("logExportIncludeLogs");

    public static string LogExportIncludeLogsDescription => GetRequiredString("logExportIncludeLogsDescription");

    public static string LogExportIncludeSystemInfo => GetRequiredString("logExportIncludeSystemInfo");

    public static string LogExportIncludeSystemInfoDescription => GetRequiredString("logExportIncludeSystemInfoDescription");

    public static string LogExportIncludeUserData => GetRequiredString("logExportIncludeUserData");

    public static string LogExportIncludeUserDataDescription => GetRequiredString("logExportIncludeUserDataDescription");

    public static string LogExportRange => GetRequiredString("logExportRange");

    public static string LogExportRangeAll => GetRequiredString("logExportRangeAll");

    public static string LogExportRangeDescription => GetRequiredString("logExportRangeDescription");

    public static string LogExportRangeEmpty => GetRequiredString("logExportRangeEmpty");

    public static string LogExportRangeGroup => GetRequiredString("logExportRangeGroup");

    public static string LogExportRangeLast24Hours => GetRequiredString("logExportRangeLast24Hours");

    public static string LogExportRangeLast30Days => GetRequiredString("logExportRangeLast30Days");

    public static string LogExportRangeLast7Days => GetRequiredString("logExportRangeLast7Days");

    public static string LogExportRangeLastHour => GetRequiredString("logExportRangeLastHour");

    public static string LogExportSucceeded => GetRequiredString("logExportSucceeded");

    public static string LogExportTitle => GetRequiredString("logExportTitle");

    public static string LogExportUserDataWarning => GetRequiredString("logExportUserDataWarning");

    public static string LogFiles => GetRequiredString("logFiles");

    public static string LogFilesDescription => GetRequiredString("logFilesDescription");

    public static string LogFilterAll => GetRequiredString("logFilterAll");

    public static string LogFilterDebug => GetRequiredString("logFilterDebug");

    public static string LogFilterError => GetRequiredString("logFilterError");

    public static string LogFilterFatal => GetRequiredString("logFilterFatal");

    public static string LogFilterInfo => GetRequiredString("logFilterInfo");

    public static string LogFilterVerbose => GetRequiredString("logFilterVerbose");

    public static string LogFilterWarn => GetRequiredString("logFilterWarn");

    public static string LogLevel => GetRequiredString("logLevel");

    public static string LogLevelDebug => GetRequiredString("logLevelDebug");

    public static string LogLevelDescription => GetRequiredString("logLevelDescription");

    public static string LogLevelError => GetRequiredString("logLevelError");

    public static string LogLevelFatal => GetRequiredString("logLevelFatal");

    public static string LogLevelInformation => GetRequiredString("logLevelInformation");

    public static string LogLevelVerbose => GetRequiredString("logLevelVerbose");

    public static string LogLevelWarning => GetRequiredString("logLevelWarning");

    public static string LogLoadEarlier => GetRequiredString("logLoadEarlier");

    public static string LogLoadFailed => GetRequiredString("logLoadFailed");

    public static string LogNoMatchingEntries => GetRequiredString("logNoMatchingEntries");

    public static string LogSearchPlaceholder => GetRequiredString("logSearchPlaceholder");

    public static string LogViewerTitle => GetRequiredString("logViewerTitle");

    public static string ManifestValidationFailed => GetRequiredString("manifestValidationFailed");

    public static string ManifestValidationPassed => GetRequiredString("manifestValidationPassed");

    public static string Minimize => GetRequiredString("minimize");

    public static string MotionMode => GetRequiredString("motionMode");

    public static string MotionModeDescription => GetRequiredString("motionModeDescription");

    public static string MotionModeFull => GetRequiredString("motionModeFull");

    public static string MotionModeReduced => GetRequiredString("motionModeReduced");

    public static string MotionModeSystem => GetRequiredString("motionModeSystem");

    public static string NetworkErrorDetail => GetRequiredString("networkErrorDetail");

    public static string NetworkLoading => GetRequiredString("networkLoading");

    public static string NeutralColorStrategy => GetRequiredString("neutralColorStrategy");

    public static string NeutralColorStrategyBrandBlue => GetRequiredString("neutralColorStrategyBrandBlue");

    public static string NeutralColorStrategyDescription => GetRequiredString("neutralColorStrategyDescription");

    public static string NeutralColorStrategySeedFollowing => GetRequiredString("neutralColorStrategySeedFollowing");

    public static string NeutralColorStrategySeedFollowingHint => GetRequiredString("neutralColorStrategySeedFollowingHint");

    public static string NextBanner => GetRequiredString("nextBanner");

    public static string Notice => GetRequiredString("notice");

    public static string NoticeConfirm => GetRequiredString("noticeConfirm");

    public static string NoticeExit => GetRequiredString("noticeExit");

    public static string OfficialSite => GetRequiredString("officialSite");

    public static string OpenColorPalette => GetRequiredString("openColorPalette");

    public static string OpenDataDirectory => GetRequiredString("openDataDirectory");

    public static string OpenDesignGallery => GetRequiredString("openDesignGallery");

    public static string OperationStopped => GetRequiredString("operationStopped");

    public static string OperationUnavailableForCurrentState => GetRequiredString("operationUnavailableForCurrentState");

    public static string Path => GetRequiredString("path");

    public static string PathLoading => GetRequiredString("pathLoading");

    public static string Pause => GetRequiredString("pause");

    public static string Paused => GetRequiredString("paused");

    public static string PauseRequested => GetRequiredString("pauseRequested");

    public static string Preparing => GetRequiredString("preparing");

    public static string PreviousBanner => GetRequiredString("previousBanner");

    public static string PrivacyPolicy => GetRequiredString("privacyPolicy");

    public static string Proxy => GetRequiredString("proxy");

    public static string ProxyAuto => GetRequiredString("proxyAuto");

    public static string ProxyDescription => GetRequiredString("proxyDescription");

    public static string ProxyDirect => GetRequiredString("proxyDirect");

    public static string ProxySystem => GetRequiredString("proxySystem");

    public static string ReadyToUninstall => GetRequiredString("readyToUninstall");

    public static string Refresh => GetRequiredString("refresh");

    public static string RefreshThemeColorPalette => GetRequiredString("refreshThemeColorPalette");

    public static string RefreshTooltip => GetRequiredString("refreshTooltip");

    public static string RememberWindowPositionAndSize => GetRequiredString("rememberWindowPositionAndSize");

    public static string RememberWindowPositionAndSizeDescription => GetRequiredString("rememberWindowPositionAndSizeDescription");

    public static string RemoteContentCard => GetRequiredString("remoteContentCard");

    public static string RemoteContentCardDescription => GetRequiredString("remoteContentCardDescription");

    public static string RemoteContentLoadFailed => GetRequiredString("remoteContentLoadFailed");

    public static string RemoteContentLoading => GetRequiredString("remoteContentLoading");

    public static string Repair => GetRequiredString("repair");

    public static string RepairCheckingFiles => GetRequiredString("repairCheckingFiles");

    public static string RepairCompleted => GetRequiredString("repairCompleted");

    public static string RepairConfirm => GetRequiredString("repairConfirm");

    public static string RepairFilesNeeded => GetRequiredString("repairFilesNeeded");

    public static string Repairing => GetRequiredString("repairing");

    public static string RepairNoChanges => GetRequiredString("repairNoChanges");

    public static string RepairNoFilesNeeded => GetRequiredString("repairNoFilesNeeded");

    public static string RepairWarning => GetRequiredString("repairWarning");

    public static string ResourcePanel => GetRequiredString("resourcePanel");

    public static string ResourcePanelCafeOnlyMessage => GetRequiredString("resourcePanelCafeOnlyMessage");

    public static string ResourcePanelCafeOnlySwitch => GetRequiredString("resourcePanelCafeOnlySwitch");

    public static string ResourcePanelCafeOnlyTitle => GetRequiredString("resourcePanelCafeOnlyTitle");

    public static string ResourcePanelChangeUid => GetRequiredString("resourcePanelChangeUid");

    public static string ResourcePanelCurrentUid => GetRequiredString("resourcePanelCurrentUid");

    public static string ResourcePanelDescription => GetRequiredString("resourcePanelDescription");

    public static string ResourcePanelEditUid => GetRequiredString("resourcePanelEditUid");

    public static string ResourcePanelFailed => GetRequiredString("resourcePanelFailed");

    public static string ResourcePanelGameText => GetRequiredString("resourcePanelGameText");

    public static string ResourcePanelLoadFailed => GetRequiredString("resourcePanelLoadFailed");

    public static string ResourcePanelLoading => GetRequiredString("resourcePanelLoading");

    public static string ResourcePanelLocalizedVersion => GetRequiredString("resourcePanelLocalizedVersion");

    public static string ResourcePanelMainVoice => GetRequiredString("resourcePanelMainVoice");

    public static string ResourcePanelManualUid => GetRequiredString("resourcePanelManualUid");

    public static string ResourcePanelMedia => GetRequiredString("resourcePanelMedia");

    public static string ResourcePanelOfficialVersion => GetRequiredString("resourcePanelOfficialVersion");

    public static string ResourcePanelReady => GetRequiredString("resourcePanelReady");

    public static string ResourcePanelRefresh => GetRequiredString("resourcePanelRefresh");

    public static string ResourcePanelSave => GetRequiredString("resourcePanelSave");

    public static string ResourcePanelSaved => GetRequiredString("resourcePanelSaved");

    public static string ResourcePanelSaveFailed => GetRequiredString("resourcePanelSaveFailed");

    public static string ResourcePanelSaveUid => GetRequiredString("resourcePanelSaveUid");

    public static string ResourcePanelUid => GetRequiredString("resourcePanelUid");

    public static string ResourcePanelUidEmpty => GetRequiredString("resourcePanelUidEmpty");

    public static string ResourcePanelUidGenerationHint => GetRequiredString("resourcePanelUidGenerationHint");

    public static string ResourcePanelUidInvalidFormat => GetRequiredString("resourcePanelUidInvalidFormat");

    public static string ResourcePanelUidMissing => GetRequiredString("resourcePanelUidMissing");

    public static string ResourcePanelUidSaved => GetRequiredString("resourcePanelUidSaved");

    public static string ResourcePanelUidSource => GetRequiredString("resourcePanelUidSource");

    public static string ResourcePanelUidSourceAuto => GetRequiredString("resourcePanelUidSourceAuto");

    public static string ResourcePanelUidSourceCustom => GetRequiredString("resourcePanelUidSourceCustom");

    public static string ResourcePanelVersionAligned => GetRequiredString("resourcePanelVersionAligned");

    public static string ResourcePanelWaiting => GetRequiredString("resourcePanelWaiting");

    public static string Resume => GetRequiredString("resume");

    public static string ResumeRequested => GetRequiredString("resumeRequested");

    public static string Retry => GetRequiredString("retry");

    public static string Save => GetRequiredString("save");

    public static string SelectInstalledGame => GetRequiredString("selectInstalledGame");

    public static string SelectInstalledGameTooltip => GetRequiredString("selectInstalledGameTooltip");

    public static string Settings => GetRequiredString("settings");

    public static string SettingsCategoryAbout => GetRequiredString("settingsCategoryAbout");

    public static string SettingsCategoryAboutDescription => GetRequiredString("settingsCategoryAboutDescription");

    public static string SettingsCategoryAdvanced => GetRequiredString("settingsCategoryAdvanced");

    public static string SettingsCategoryAdvancedDescription => GetRequiredString("settingsCategoryAdvancedDescription");

    public static string SettingsCategoryAppearance => GetRequiredString("settingsCategoryAppearance");

    public static string SettingsCategoryAppearanceDescription => GetRequiredString("settingsCategoryAppearanceDescription");

    public static string SettingsCategoryDownloadNetwork => GetRequiredString("settingsCategoryDownloadNetwork");

    public static string SettingsCategoryDownloadNetworkDescription => GetRequiredString("settingsCategoryDownloadNetworkDescription");

    public static string SettingsCategoryGame => GetRequiredString("settingsCategoryGame");

    public static string SettingsCategoryGameDescription => GetRequiredString("settingsCategoryGameDescription");

    public static string SettingsCategoryGeneral => GetRequiredString("settingsCategoryGeneral");

    public static string SettingsCategoryGeneralDescription => GetRequiredString("settingsCategoryGeneralDescription");

    public static string SettingsGroupAppPreferences => GetRequiredString("settingsGroupAppPreferences");

    public static string SettingsGroupBackground => GetRequiredString("settingsGroupBackground");

    public static string SettingsGroupConnection => GetRequiredString("settingsGroupConnection");

    public static string SettingsGroupDiagnostics => GetRequiredString("settingsGroupDiagnostics");

    public static string SettingsGroupDisplay => GetRequiredString("settingsGroupDisplay");

    public static string SettingsGroupGameFiles => GetRequiredString("settingsGroupGameFiles");

    public static string SettingsGroupGameRuntime => GetRequiredString("settingsGroupGameRuntime");

    public static string SettingsGroupThemeColor => GetRequiredString("settingsGroupThemeColor");

    public static string SettingsGroupUpdates => GetRequiredString("settingsGroupUpdates");

    public static string SettingsSaved => GetRequiredString("settingsSaved");

    public static string SettingsSaveFailed => GetRequiredString("settingsSaveFailed");

    public static string SettingsSummaryWithTheme => GetRequiredString("settingsSummaryWithTheme");

    public static string SetupWizardBrowse => GetRequiredString("setupWizardBrowse");

    public static string SetupWizardDownloadSource => GetRequiredString("setupWizardDownloadSource");

    public static string SetupWizardDownloadSourceCafeDescription => GetRequiredString("setupWizardDownloadSourceCafeDescription");

    public static string SetupWizardDownloadSourceCafeRecommendationReason => GetRequiredString("setupWizardDownloadSourceCafeRecommendationReason");

    public static string SetupWizardDownloadSourceHint => GetRequiredString("setupWizardDownloadSourceHint");

    public static string SetupWizardDownloadSourceOfficialDescription => GetRequiredString("setupWizardDownloadSourceOfficialDescription");

    public static string SetupWizardEditStep => GetRequiredString("setupWizardEditStep");

    public static string SetupWizardExitConfirm => GetRequiredString("setupWizardExitConfirm");

    public static string SetupWizardExitMessage => GetRequiredString("setupWizardExitMessage");

    public static string SetupWizardExitTitle => GetRequiredString("setupWizardExitTitle");

    public static string SetupWizardFinish => GetRequiredString("setupWizardFinish");

    public static string SetupWizardGamePath => GetRequiredString("setupWizardGamePath");

    public static string SetupWizardGamePathAvailable => GetRequiredString("setupWizardGamePathAvailable");

    public static string SetupWizardGamePathChecking => GetRequiredString("setupWizardGamePathChecking");

    public static string SetupWizardGamePathCorrupted => GetRequiredString("setupWizardGamePathCorrupted");

    public static string SetupWizardGamePathEmpty => GetRequiredString("setupWizardGamePathEmpty");

    public static string SetupWizardGamePathHint => GetRequiredString("setupWizardGamePathHint");

    public static string SetupWizardGamePathInaccessible => GetRequiredString("setupWizardGamePathInaccessible");

    public static string SetupWizardGamePathInstalled => GetRequiredString("setupWizardGamePathInstalled");

    public static string SetupWizardGamePathNotWritable => GetRequiredString("setupWizardGamePathNotWritable");

    public static string SetupWizardGamePathStatusTitle => GetRequiredString("setupWizardGamePathStatusTitle");

    public static string SetupWizardLanguage => GetRequiredString("setupWizardLanguage");

    public static string SetupWizardLanguageHint => GetRequiredString("setupWizardLanguageHint");

    public static string SetupWizardNext => GetRequiredString("setupWizardNext");

    public static string SetupWizardPrevious => GetRequiredString("setupWizardPrevious");

    public static string SetupWizardProxy => GetRequiredString("setupWizardProxy");

    public static string SetupWizardProxyAutoDescription => GetRequiredString("setupWizardProxyAutoDescription");

    public static string SetupWizardProxyDirectDescription => GetRequiredString("setupWizardProxyDirectDescription");

    public static string SetupWizardProxyHint => GetRequiredString("setupWizardProxyHint");

    public static string SetupWizardProxySystemDescription => GetRequiredString("setupWizardProxySystemDescription");

    public static string SetupWizardReview => GetRequiredString("setupWizardReview");

    public static string SetupWizardReviewHint => GetRequiredString("setupWizardReviewHint");

    public static string SetupWizardSkip => GetRequiredString("setupWizardSkip");

    public static string SetupWizardStepTitle => GetRequiredString("setupWizardStepTitle");

    public static string SetupWizardWelcomeText => GetRequiredString("setupWizardWelcomeText");

    public static string ShowLauncher => GetRequiredString("showLauncher");

    public static string Speed10MBs => GetRequiredString("speed10MBs");

    public static string Speed1MBs => GetRequiredString("speed1MBs");

    public static string Speed25MBs => GetRequiredString("speed25MBs");

    public static string Speed50MBs => GetRequiredString("speed50MBs");

    public static string Speed5MBs => GetRequiredString("speed5MBs");

    public static string SpeedUnlimited => GetRequiredString("speedUnlimited");

    public static string StartGame => GetRequiredString("startGame");

    public static string StartupUpdateAvailable => GetRequiredString("startupUpdateAvailable");

    public static string StatusDetailMode => GetRequiredString("statusDetailMode");

    public static string StatusDetailModeCompact => GetRequiredString("statusDetailModeCompact");

    public static string StatusDetailModeDescription => GetRequiredString("statusDetailModeDescription");

    public static string StatusDetailModeHidden => GetRequiredString("statusDetailModeHidden");

    public static string StatusLaunchCheckLocal => GetRequiredString("statusLaunchCheckLocal");

    public static string StatusLaunchCheckNone => GetRequiredString("statusLaunchCheckNone");

    public static string StatusLaunchCheckRemote => GetRequiredString("statusLaunchCheckRemote");

    public static string StatusNetworkLoaded => GetRequiredString("statusNetworkLoaded");

    public static string Stop => GetRequiredString("stop");

    public static string StopAndExit => GetRequiredString("stopAndExit");

    public static string StopDownloadMessage => GetRequiredString("stopDownloadMessage");

    public static string StopDownloadTitle => GetRequiredString("stopDownloadTitle");

    public static string StopRequested => GetRequiredString("stopRequested");

    public static string Theme => GetRequiredString("theme");

    public static string ThemeColor => GetRequiredString("themeColor");

    public static string ThemeColorCustom => GetRequiredString("themeColorCustom");

    public static string ThemeColorDefault => GetRequiredString("themeColorDefault");

    public static string ThemeColorDescription => GetRequiredString("themeColorDescription");

    public static string ThemeColorExtractionAlgorithm => GetRequiredString("themeColorExtractionAlgorithm");

    public static string ThemeColorExtractionAlgorithmCelebiScore => GetRequiredString("themeColorExtractionAlgorithmCelebiScore");

    public static string ThemeColorExtractionAlgorithmDescription => GetRequiredString("themeColorExtractionAlgorithmDescription");

    public static string ThemeColorExtractionAlgorithmOctree => GetRequiredString("themeColorExtractionAlgorithmOctree");

    public static string ThemeColorExtractionAlgorithmWsmeans => GetRequiredString("themeColorExtractionAlgorithmWsmeans");

    public static string ThemeColorExtractionAlgorithmWu => GetRequiredString("themeColorExtractionAlgorithmWu");

    public static string ThemeColorPalette => GetRequiredString("themeColorPalette");

    public static string ThemeColorPaletteDescription => GetRequiredString("themeColorPaletteDescription");

    public static string ThemeColorSystem => GetRequiredString("themeColorSystem");

    public static string ThemeColorVariant => GetRequiredString("themeColorVariant");

    public static string ThemeColorVariantContent => GetRequiredString("themeColorVariantContent");

    public static string ThemeColorVariantDescription => GetRequiredString("themeColorVariantDescription");

    public static string ThemeColorVariantExpressive => GetRequiredString("themeColorVariantExpressive");

    public static string ThemeColorVariantFidelity => GetRequiredString("themeColorVariantFidelity");

    public static string ThemeColorVariantMonochrome => GetRequiredString("themeColorVariantMonochrome");

    public static string ThemeColorVariantNeutral => GetRequiredString("themeColorVariantNeutral");

    public static string ThemeColorVariantRainbow => GetRequiredString("themeColorVariantRainbow");

    public static string ThemeColorVariantTonalSpot => GetRequiredString("themeColorVariantTonalSpot");

    public static string ThemeColorVariantVibrant => GetRequiredString("themeColorVariantVibrant");

    public static string ThemeColorWallpaper => GetRequiredString("themeColorWallpaper");

    public static string ThemeDark => GetRequiredString("themeDark");

    public static string ThemeDescription => GetRequiredString("themeDescription");

    public static string ThemeLight => GetRequiredString("themeLight");

    public static string ThemeSystem => GetRequiredString("themeSystem");

    public static string ToastActionFailedMessage => GetRequiredString("toastActionFailedMessage");

    public static string ToastActionFailedTitle => GetRequiredString("toastActionFailedTitle");

    public static string ToastError => GetRequiredString("toastError");

    public static string ToastInfo => GetRequiredString("toastInfo");

    public static string ToastRegionName => GetRequiredString("toastRegionName");

    public static string ToastSuccess => GetRequiredString("toastSuccess");

    public static string ToastWarning => GetRequiredString("toastWarning");

    public static string ToggleOff => GetRequiredString("toggleOff");

    public static string ToggleOn => GetRequiredString("toggleOn");

    public static string TrayExitLauncher => GetRequiredString("trayExitLauncher");

    public static string TrayOpenLauncher => GetRequiredString("trayOpenLauncher");

    public static string UnexpectedError => GetRequiredString("unexpectedError");

    public static string Uninstall => GetRequiredString("uninstall");

    public static string UninstallCompleted => GetRequiredString("uninstallCompleted");

    public static string UninstallCompletedKeptPrefix => GetRequiredString("uninstallCompletedKeptPrefix");

    public static string UninstallCompletedWithLeftovers => GetRequiredString("uninstallCompletedWithLeftovers");

    public static string UninstallCompletedWithLeftoversKeptPrefix => GetRequiredString("uninstallCompletedWithLeftoversKeptPrefix");

    public static string UninstallConfirmText => GetRequiredString("uninstallConfirmText");

    public static string UninstallFailed => GetRequiredString("uninstallFailed");

    public static string Uninstalling => GetRequiredString("uninstalling");

    public static string UninstallRefusedByPathGuard => GetRequiredString("uninstallRefusedByPathGuard");

    public static string UninstallThoroughCleanupOption => GetRequiredString("uninstallThoroughCleanupOption");

    public static string UninstallThoroughCleanupOptionPending => GetRequiredString("uninstallThoroughCleanupOptionPending");

    public static string Unknown => GetRequiredString("unknown");

    public static string UnsavedChanges => GetRequiredString("unsavedChanges");

    public static string UnsavedChangesMessage => GetRequiredString("unsavedChangesMessage");

    public static string UpdateAvailable => GetRequiredString("updateAvailable");

    public static string UpdateCheckingFiles => GetRequiredString("updateCheckingFiles");

    public static string UpdateGame => GetRequiredString("updateGame");

    public static string VerificationFailed => GetRequiredString("verificationFailed");

    public static string VerificationRetry => GetRequiredString("verificationRetry");

    public static string VerifyingDownloadedFiles => GetRequiredString("verifyingDownloadedFiles");

    public static string VersionInfo => GetRequiredString("versionInfo");

    public static string VersionInstalled => GetRequiredString("versionInstalled");

    public static string VersionLatest => GetRequiredString("versionLatest");

    public static string VersionLoading => GetRequiredString("versionLoading");

    public static string VersionUnavailable => GetRequiredString("versionUnavailable");

    public static string ViewLog => GetRequiredString("viewLog");

    public static string Working => GetRequiredString("working");
}
