// <auto-generated>
//     Generated by scripts/Generate-LocalizationKeys.ps1 from
//     Resources/LauncherStrings.resx. Do not edit by hand; rerun the script
//     after adding or renaming a resource key.
// </auto-generated>

namespace Cafe.Launcher.Avalonia.Constants;

/// <summary>
/// Compile-time names for every LauncherStrings resource key. C# call sites must
/// reference these constants instead of raw string literals so a renamed or
/// misspelled key breaks the build rather than rendering a raw key at runtime.
/// </summary>
public static class LocalizationKeys
{
    /// <summary>Resource key for <c>about</c>.</summary>
    public const string About = "about";

    /// <summary>Resource key for <c>aboutCopyrightText</c>.</summary>
    public const string AboutCopyrightText = "aboutCopyrightText";

    /// <summary>Resource key for <c>aboutDescription</c>.</summary>
    public const string AboutDescription = "aboutDescription";

    /// <summary>Resource key for <c>aboutDisclaimerText</c>.</summary>
    public const string AboutDisclaimerText = "aboutDisclaimerText";

    /// <summary>Resource key for <c>aboutLinks</c>.</summary>
    public const string AboutLinks = "aboutLinks";

    /// <summary>Resource key for <c>aboutQuickLinks</c>.</summary>
    public const string AboutQuickLinks = "aboutQuickLinks";

    /// <summary>Resource key for <c>aboutRowAvalonia</c>.</summary>
    public const string AboutRowAvalonia = "aboutRowAvalonia";

    /// <summary>Resource key for <c>aboutRowBuildConfig</c>.</summary>
    public const string AboutRowBuildConfig = "aboutRowBuildConfig";

    /// <summary>Resource key for <c>aboutRowBuildTime</c>.</summary>
    public const string AboutRowBuildTime = "aboutRowBuildTime";

    /// <summary>Resource key for <c>aboutRowCommit</c>.</summary>
    public const string AboutRowCommit = "aboutRowCommit";

    /// <summary>Resource key for <c>aboutRowPlatform</c>.</summary>
    public const string AboutRowPlatform = "aboutRowPlatform";

    /// <summary>Resource key for <c>aboutRowRuntime</c>.</summary>
    public const string AboutRowRuntime = "aboutRowRuntime";

    /// <summary>Resource key for <c>aboutRowVersion</c>.</summary>
    public const string AboutRowVersion = "aboutRowVersion";

    /// <summary>Resource key for <c>aboutVersionCaption</c>.</summary>
    public const string AboutVersionCaption = "aboutVersionCaption";

    /// <summary>Resource key for <c>apiFailedNoFileChange</c>.</summary>
    public const string ApiFailedNoFileChange = "apiFailedNoFileChange";

    /// <summary>Resource key for <c>appearancePreviewFailed</c>.</summary>
    public const string AppearancePreviewFailed = "appearancePreviewFailed";

    /// <summary>Resource key for <c>backgroundFillColor</c>.</summary>
    public const string BackgroundFillColor = "backgroundFillColor";

    /// <summary>Resource key for <c>backgroundFillColorDescription</c>.</summary>
    public const string BackgroundFillColorDescription = "backgroundFillColorDescription";

    /// <summary>Resource key for <c>backgroundFit</c>.</summary>
    public const string BackgroundFit = "backgroundFit";

    /// <summary>Resource key for <c>backgroundFitDescription</c>.</summary>
    public const string BackgroundFitDescription = "backgroundFitDescription";

    /// <summary>Resource key for <c>backgroundFitFill</c>.</summary>
    public const string BackgroundFitFill = "backgroundFitFill";

    /// <summary>Resource key for <c>backgroundFitUniform</c>.</summary>
    public const string BackgroundFitUniform = "backgroundFitUniform";

    /// <summary>Resource key for <c>backgroundFitUniformToFill</c>.</summary>
    public const string BackgroundFitUniformToFill = "backgroundFitUniformToFill";

    /// <summary>Resource key for <c>backgroundSource</c>.</summary>
    public const string BackgroundSource = "backgroundSource";

    /// <summary>Resource key for <c>backgroundSourceBundled</c>.</summary>
    public const string BackgroundSourceBundled = "backgroundSourceBundled";

    /// <summary>Resource key for <c>backgroundSourceCustom</c>.</summary>
    public const string BackgroundSourceCustom = "backgroundSourceCustom";

    /// <summary>Resource key for <c>backgroundSourceDescription</c>.</summary>
    public const string BackgroundSourceDescription = "backgroundSourceDescription";

    /// <summary>Resource key for <c>backgroundSourceRemote</c>.</summary>
    public const string BackgroundSourceRemote = "backgroundSourceRemote";

    /// <summary>Resource key for <c>banner</c>.</summary>
    public const string Banner = "banner";

    /// <summary>Resource key for <c>bannerLoading</c>.</summary>
    public const string BannerLoading = "bannerLoading";

    /// <summary>Resource key for <c>bannerLoadingFailed</c>.</summary>
    public const string BannerLoadingFailed = "bannerLoadingFailed";

    /// <summary>Resource key for <c>banners</c>.</summary>
    public const string Banners = "banners";

    /// <summary>Resource key for <c>buildInfo</c>.</summary>
    public const string BuildInfo = "buildInfo";

    /// <summary>Resource key for <c>buildingFileList</c>.</summary>
    public const string BuildingFileList = "buildingFileList";

    /// <summary>Resource key for <c>busy</c>.</summary>
    public const string Busy = "busy";

    /// <summary>Resource key for <c>cancel</c>.</summary>
    public const string Cancel = "cancel";

    /// <summary>Resource key for <c>carouselPage</c>.</summary>
    public const string CarouselPage = "carouselPage";

    /// <summary>Resource key for <c>cdnConfigIncomplete</c>.</summary>
    public const string CdnConfigIncomplete = "cdnConfigIncomplete";

    /// <summary>Resource key for <c>changePath</c>.</summary>
    public const string ChangePath = "changePath";

    /// <summary>Resource key for <c>checkUpdates</c>.</summary>
    public const string CheckUpdates = "checkUpdates";

    /// <summary>Resource key for <c>choose</c>.</summary>
    public const string Choose = "choose";

    /// <summary>Resource key for <c>chooseBackgroundFolderTitle</c>.</summary>
    public const string ChooseBackgroundFolderTitle = "chooseBackgroundFolderTitle";

    /// <summary>Resource key for <c>chooseBackgroundImageTitle</c>.</summary>
    public const string ChooseBackgroundImageTitle = "chooseBackgroundImageTitle";

    /// <summary>Resource key for <c>chooseFolder</c>.</summary>
    public const string ChooseFolder = "chooseFolder";

    /// <summary>Resource key for <c>chooseImage</c>.</summary>
    public const string ChooseImage = "chooseImage";

    /// <summary>Resource key for <c>chooseInstallFolder</c>.</summary>
    public const string ChooseInstallFolder = "chooseInstallFolder";

    /// <summary>Resource key for <c>choosePathInstall</c>.</summary>
    public const string ChoosePathInstall = "choosePathInstall";

    /// <summary>Resource key for <c>clearBackground</c>.</summary>
    public const string ClearBackground = "clearBackground";

    /// <summary>Resource key for <c>close</c>.</summary>
    public const string Close = "close";

    /// <summary>Resource key for <c>closeBehavior</c>.</summary>
    public const string CloseBehavior = "closeBehavior";

    /// <summary>Resource key for <c>closeBehaviorDescription</c>.</summary>
    public const string CloseBehaviorDescription = "closeBehaviorDescription";

    /// <summary>Resource key for <c>closeBehaviorExit</c>.</summary>
    public const string CloseBehaviorExit = "closeBehaviorExit";

    /// <summary>Resource key for <c>closeBehaviorMinimize</c>.</summary>
    public const string CloseBehaviorMinimize = "closeBehaviorMinimize";

    /// <summary>Resource key for <c>confirmUninstall</c>.</summary>
    public const string ConfirmUninstall = "confirmUninstall";

    /// <summary>Resource key for <c>connectingApi</c>.</summary>
    public const string ConnectingApi = "connectingApi";

    /// <summary>Resource key for <c>contactCustomerSupport</c>.</summary>
    public const string ContactCustomerSupport = "contactCustomerSupport";

    /// <summary>Resource key for <c>copyright</c>.</summary>
    public const string Copyright = "copyright";

    /// <summary>Resource key for <c>customBackground</c>.</summary>
    public const string CustomBackground = "customBackground";

    /// <summary>Resource key for <c>customBackgroundDescription</c>.</summary>
    public const string CustomBackgroundDescription = "customBackgroundDescription";

    /// <summary>Resource key for <c>debugActionFailureMessage</c>.</summary>
    public const string DebugActionFailureMessage = "debugActionFailureMessage";

    /// <summary>Resource key for <c>debugActionFailureTitle</c>.</summary>
    public const string DebugActionFailureTitle = "debugActionFailureTitle";

    /// <summary>Resource key for <c>debugActionToastMessage</c>.</summary>
    public const string DebugActionToastMessage = "debugActionToastMessage";

    /// <summary>Resource key for <c>debugActionToastTitle</c>.</summary>
    public const string DebugActionToastTitle = "debugActionToastTitle";

    /// <summary>Resource key for <c>debugCriticalErrorMessage</c>.</summary>
    public const string DebugCriticalErrorMessage = "debugCriticalErrorMessage";

    /// <summary>Resource key for <c>debugCriticalErrorTriggered</c>.</summary>
    public const string DebugCriticalErrorTriggered = "debugCriticalErrorTriggered";

    /// <summary>Resource key for <c>debugExportCancelled</c>.</summary>
    public const string DebugExportCancelled = "debugExportCancelled";

    /// <summary>Resource key for <c>debugGameOperations</c>.</summary>
    public const string DebugGameOperations = "debugGameOperations";

    /// <summary>Resource key for <c>debugHandledErrorMessage</c>.</summary>
    public const string DebugHandledErrorMessage = "debugHandledErrorMessage";

    /// <summary>Resource key for <c>debugHandledErrorSimulated</c>.</summary>
    public const string DebugHandledErrorSimulated = "debugHandledErrorSimulated";

    /// <summary>Resource key for <c>debugIdle</c>.</summary>
    public const string DebugIdle = "debugIdle";

    /// <summary>Resource key for <c>debugLogEntryWritten</c>.</summary>
    public const string DebugLogEntryWritten = "debugLogEntryWritten";

    /// <summary>Resource key for <c>debugLogExportUnavailable</c>.</summary>
    public const string DebugLogExportUnavailable = "debugLogExportUnavailable";

    /// <summary>Resource key for <c>debugLogLevelSet</c>.</summary>
    public const string DebugLogLevelSet = "debugLogLevelSet";

    /// <summary>Resource key for <c>debugOutput</c>.</summary>
    public const string DebugOutput = "debugOutput";

    /// <summary>Resource key for <c>debugPanel</c>.</summary>
    public const string DebugPanel = "debugPanel";

    /// <summary>Resource key for <c>debugPauseResume</c>.</summary>
    public const string DebugPauseResume = "debugPauseResume";

    /// <summary>Resource key for <c>debugResetSettingsConfirm</c>.</summary>
    public const string DebugResetSettingsConfirm = "debugResetSettingsConfirm";

    /// <summary>Resource key for <c>debugResetSettingsDescription</c>.</summary>
    public const string DebugResetSettingsDescription = "debugResetSettingsDescription";

    /// <summary>Resource key for <c>debugResetSettingsTitle</c>.</summary>
    public const string DebugResetSettingsTitle = "debugResetSettingsTitle";

    /// <summary>Resource key for <c>debugSettingsReadFailed</c>.</summary>
    public const string DebugSettingsReadFailed = "debugSettingsReadFailed";

    /// <summary>Resource key for <c>debugSettingsReset</c>.</summary>
    public const string DebugSettingsReset = "debugSettingsReset";

    /// <summary>Resource key for <c>debugSimulateError</c>.</summary>
    public const string DebugSimulateError = "debugSimulateError";

    /// <summary>Resource key for <c>debugSimulateFailure</c>.</summary>
    public const string DebugSimulateFailure = "debugSimulateFailure";

    /// <summary>Resource key for <c>debugSimulateSuccess</c>.</summary>
    public const string DebugSimulateSuccess = "debugSimulateSuccess";

    /// <summary>Resource key for <c>debugStateRefreshTriggered</c>.</summary>
    public const string DebugStateRefreshTriggered = "debugStateRefreshTriggered";

    /// <summary>Resource key for <c>debugStatus</c>.</summary>
    public const string DebugStatus = "debugStatus";

    /// <summary>Resource key for <c>debugSystemInfo</c>.</summary>
    public const string DebugSystemInfo = "debugSystemInfo";

    /// <summary>Resource key for <c>debugSystemInfoFormat</c>.</summary>
    public const string DebugSystemInfoFormat = "debugSystemInfoFormat";

    /// <summary>Resource key for <c>debugTestActionToast</c>.</summary>
    public const string DebugTestActionToast = "debugTestActionToast";

    /// <summary>Resource key for <c>debugTestErrorToast</c>.</summary>
    public const string DebugTestErrorToast = "debugTestErrorToast";

    /// <summary>Resource key for <c>debugTestInfoToast</c>.</summary>
    public const string DebugTestInfoToast = "debugTestInfoToast";

    /// <summary>Resource key for <c>debugTestLogMessage</c>.</summary>
    public const string DebugTestLogMessage = "debugTestLogMessage";

    /// <summary>Resource key for <c>debugTestSuccessToast</c>.</summary>
    public const string DebugTestSuccessToast = "debugTestSuccessToast";

    /// <summary>Resource key for <c>debugTestToastMessage</c>.</summary>
    public const string DebugTestToastMessage = "debugTestToastMessage";

    /// <summary>Resource key for <c>debugTestWarningToast</c>.</summary>
    public const string DebugTestWarningToast = "debugTestWarningToast";

    /// <summary>Resource key for <c>debugToastShown</c>.</summary>
    public const string DebugToastShown = "debugToastShown";

    /// <summary>Resource key for <c>defaultBackgroundArtwork</c>.</summary>
    public const string DefaultBackgroundArtwork = "defaultBackgroundArtwork";

    /// <summary>Resource key for <c>defaultBackgroundCopyrightText</c>.</summary>
    public const string DefaultBackgroundCopyrightText = "defaultBackgroundCopyrightText";

    /// <summary>Resource key for <c>deletingManifestFiles</c>.</summary>
    public const string DeletingManifestFiles = "deletingManifestFiles";

    /// <summary>Resource key for <c>designGalleryHint</c>.</summary>
    public const string DesignGalleryHint = "designGalleryHint";

    /// <summary>Resource key for <c>designGalleryTitle</c>.</summary>
    public const string DesignGalleryTitle = "designGalleryTitle";

    /// <summary>Resource key for <c>designGroupBorder</c>.</summary>
    public const string DesignGroupBorder = "designGroupBorder";

    /// <summary>Resource key for <c>designGroupColor</c>.</summary>
    public const string DesignGroupColor = "designGroupColor";

    /// <summary>Resource key for <c>designGroupComponent</c>.</summary>
    public const string DesignGroupComponent = "designGroupComponent";

    /// <summary>Resource key for <c>designGroupControl</c>.</summary>
    public const string DesignGroupControl = "designGroupControl";

    /// <summary>Resource key for <c>designGroupElevation</c>.</summary>
    public const string DesignGroupElevation = "designGroupElevation";

    /// <summary>Resource key for <c>designGroupIcon</c>.</summary>
    public const string DesignGroupIcon = "designGroupIcon";

    /// <summary>Resource key for <c>designGroupLayout</c>.</summary>
    public const string DesignGroupLayout = "designGroupLayout";

    /// <summary>Resource key for <c>designGroupMotion</c>.</summary>
    public const string DesignGroupMotion = "designGroupMotion";

    /// <summary>Resource key for <c>designGroupOther</c>.</summary>
    public const string DesignGroupOther = "designGroupOther";

    /// <summary>Resource key for <c>designGroupRadius</c>.</summary>
    public const string DesignGroupRadius = "designGroupRadius";

    /// <summary>Resource key for <c>designGroupSpacing</c>.</summary>
    public const string DesignGroupSpacing = "designGroupSpacing";

    /// <summary>Resource key for <c>designGroupStateLayer</c>.</summary>
    public const string DesignGroupStateLayer = "designGroupStateLayer";

    /// <summary>Resource key for <c>designGroupText</c>.</summary>
    public const string DesignGroupText = "designGroupText";

    /// <summary>Resource key for <c>designGroupTypography</c>.</summary>
    public const string DesignGroupTypography = "designGroupTypography";

    /// <summary>Resource key for <c>designMatrixCardWithToast</c>.</summary>
    public const string DesignMatrixCardWithToast = "designMatrixCardWithToast";

    /// <summary>Resource key for <c>designMatrixErrorButton</c>.</summary>
    public const string DesignMatrixErrorButton = "designMatrixErrorButton";

    /// <summary>Resource key for <c>designMatrixFilledButton</c>.</summary>
    public const string DesignMatrixFilledButton = "designMatrixFilledButton";

    /// <summary>Resource key for <c>designMatrixOutlinedButton</c>.</summary>
    public const string DesignMatrixOutlinedButton = "designMatrixOutlinedButton";

    /// <summary>Resource key for <c>designMatrixSettingsRow</c>.</summary>
    public const string DesignMatrixSettingsRow = "designMatrixSettingsRow";

    /// <summary>Resource key for <c>designMatrixTextButton</c>.</summary>
    public const string DesignMatrixTextButton = "designMatrixTextButton";

    /// <summary>Resource key for <c>designStateDisabled</c>.</summary>
    public const string DesignStateDisabled = "designStateDisabled";

    /// <summary>Resource key for <c>designStateFocus</c>.</summary>
    public const string DesignStateFocus = "designStateFocus";

    /// <summary>Resource key for <c>designStateHover</c>.</summary>
    public const string DesignStateHover = "designStateHover";

    /// <summary>Resource key for <c>designStateInvalid</c>.</summary>
    public const string DesignStateInvalid = "designStateInvalid";

    /// <summary>Resource key for <c>designStateNormal</c>.</summary>
    public const string DesignStateNormal = "designStateNormal";

    /// <summary>Resource key for <c>designStatePressed</c>.</summary>
    public const string DesignStatePressed = "designStatePressed";

    /// <summary>Resource key for <c>discardChanges</c>.</summary>
    public const string DiscardChanges = "discardChanges";

    /// <summary>Resource key for <c>diskSpace</c>.</summary>
    public const string DiskSpace = "diskSpace";

    /// <summary>Resource key for <c>diskSpaceCheck</c>.</summary>
    public const string DiskSpaceCheck = "diskSpaceCheck";

    /// <summary>Resource key for <c>diskSpaceEmpty</c>.</summary>
    public const string DiskSpaceEmpty = "diskSpaceEmpty";

    /// <summary>Resource key for <c>diskSpaceInsufficient</c>.</summary>
    public const string DiskSpaceInsufficient = "diskSpaceInsufficient";

    /// <summary>Resource key for <c>diskSpaceInsufficientDetail</c>.</summary>
    public const string DiskSpaceInsufficientDetail = "diskSpaceInsufficientDetail";

    /// <summary>Resource key for <c>diskSpaceOkSuffix</c>.</summary>
    public const string DiskSpaceOkSuffix = "diskSpaceOkSuffix";

    /// <summary>Resource key for <c>diskSpaceShortSuffix</c>.</summary>
    public const string DiskSpaceShortSuffix = "diskSpaceShortSuffix";

    /// <summary>Resource key for <c>downloading</c>.</summary>
    public const string Downloading = "downloading";

    /// <summary>Resource key for <c>downloadRemoteConfigIncomplete</c>.</summary>
    public const string DownloadRemoteConfigIncomplete = "downloadRemoteConfigIncomplete";

    /// <summary>Resource key for <c>downloadSource</c>.</summary>
    public const string DownloadSource = "downloadSource";

    /// <summary>Resource key for <c>downloadSourceCafe</c>.</summary>
    public const string DownloadSourceCafe = "downloadSourceCafe";

    /// <summary>Resource key for <c>downloadSourceChangedRepairPrompt</c>.</summary>
    public const string DownloadSourceChangedRepairPrompt = "downloadSourceChangedRepairPrompt";

    /// <summary>Resource key for <c>downloadSourceDescription</c>.</summary>
    public const string DownloadSourceDescription = "downloadSourceDescription";

    /// <summary>Resource key for <c>downloadSourceOfficial</c>.</summary>
    public const string DownloadSourceOfficial = "downloadSourceOfficial";

    /// <summary>Resource key for <c>downloadSpeedLimit</c>.</summary>
    public const string DownloadSpeedLimit = "downloadSpeedLimit";

    /// <summary>Resource key for <c>downloadSpeedLimitDescription</c>.</summary>
    public const string DownloadSpeedLimitDescription = "downloadSpeedLimitDescription";

    /// <summary>Resource key for <c>enableStartupUpdateCheck</c>.</summary>
    public const string EnableStartupUpdateCheck = "enableStartupUpdateCheck";

    /// <summary>Resource key for <c>enableStartupUpdateCheckDescription</c>.</summary>
    public const string EnableStartupUpdateCheckDescription = "enableStartupUpdateCheckDescription";

    /// <summary>Resource key for <c>errorDialogContinue</c>.</summary>
    public const string ErrorDialogContinue = "errorDialogContinue";

    /// <summary>Resource key for <c>errorDialogCopyDetails</c>.</summary>
    public const string ErrorDialogCopyDetails = "errorDialogCopyDetails";

    /// <summary>Resource key for <c>errorDialogDescription</c>.</summary>
    public const string ErrorDialogDescription = "errorDialogDescription";

    /// <summary>Resource key for <c>errorDialogTitle</c>.</summary>
    public const string ErrorDialogTitle = "errorDialogTitle";

    /// <summary>Resource key for <c>errorDialogViewLog</c>.</summary>
    public const string ErrorDialogViewLog = "errorDialogViewLog";

    /// <summary>Resource key for <c>estimatedTimeRemaining</c>.</summary>
    public const string EstimatedTimeRemaining = "estimatedTimeRemaining";

    /// <summary>Resource key for <c>executable</c>.</summary>
    public const string Executable = "executable";

    /// <summary>Resource key for <c>executableLoading</c>.</summary>
    public const string ExecutableLoading = "executableLoading";

    /// <summary>Resource key for <c>executableNameValue</c>.</summary>
    public const string ExecutableNameValue = "executableNameValue";

    /// <summary>Resource key for <c>executableValue</c>.</summary>
    public const string ExecutableValue = "executableValue";

    /// <summary>Resource key for <c>exitLauncher</c>.</summary>
    public const string ExitLauncher = "exitLauncher";

    /// <summary>Resource key for <c>exportLogs</c>.</summary>
    public const string ExportLogs = "exportLogs";

    /// <summary>Resource key for <c>fileAccessDenied</c>.</summary>
    public const string FileAccessDenied = "fileAccessDenied";

    /// <summary>Resource key for <c>fileOperationFailed</c>.</summary>
    public const string FileOperationFailed = "fileOperationFailed";

    /// <summary>Resource key for <c>folderPickerUnavailable</c>.</summary>
    public const string FolderPickerUnavailable = "folderPickerUnavailable";

    /// <summary>Resource key for <c>gameAlreadyCurrent</c>.</summary>
    public const string GameAlreadyCurrent = "gameAlreadyCurrent";

    /// <summary>Resource key for <c>gameBelowLowestVersion</c>.</summary>
    public const string GameBelowLowestVersion = "gameBelowLowestVersion";

    /// <summary>Resource key for <c>gameCheckUpdate</c>.</summary>
    public const string GameCheckUpdate = "gameCheckUpdate";

    /// <summary>Resource key for <c>gameCheckUpdateAvailable</c>.</summary>
    public const string GameCheckUpdateAvailable = "gameCheckUpdateAvailable";

    /// <summary>Resource key for <c>gameCheckUpdateFailed</c>.</summary>
    public const string GameCheckUpdateFailed = "gameCheckUpdateFailed";

    /// <summary>Resource key for <c>gameCheckUpdateUpToDate</c>.</summary>
    public const string GameCheckUpdateUpToDate = "gameCheckUpdateUpToDate";

    /// <summary>Resource key for <c>gameConfigMetadataMissing</c>.</summary>
    public const string GameConfigMetadataMissing = "gameConfigMetadataMissing";

    /// <summary>Resource key for <c>gameCorruptedInstallationState</c>.</summary>
    public const string GameCorruptedInstallationState = "gameCorruptedInstallationState";

    /// <summary>Resource key for <c>gameCreateShortcut</c>.</summary>
    public const string GameCreateShortcut = "gameCreateShortcut";

    /// <summary>Resource key for <c>gameDirectoryNameInvalid</c>.</summary>
    public const string GameDirectoryNameInvalid = "gameDirectoryNameInvalid";

    /// <summary>Resource key for <c>gameDisplayName</c>.</summary>
    public const string GameDisplayName = "gameDisplayName";

    /// <summary>Resource key for <c>gameExecutableMissing</c>.</summary>
    public const string GameExecutableMissing = "gameExecutableMissing";

    /// <summary>Resource key for <c>gameExecutableNameEmpty</c>.</summary>
    public const string GameExecutableNameEmpty = "gameExecutableNameEmpty";

    /// <summary>Resource key for <c>gameExecutableNameInvalid</c>.</summary>
    public const string GameExecutableNameInvalid = "gameExecutableNameInvalid";

    /// <summary>Resource key for <c>gameExecutableRunning</c>.</summary>
    public const string GameExecutableRunning = "gameExecutableRunning";

    /// <summary>Resource key for <c>gameFolderMissing</c>.</summary>
    public const string GameFolderMissing = "gameFolderMissing";

    /// <summary>Resource key for <c>gameInstallationStateReadFailed</c>.</summary>
    public const string GameInstallationStateReadFailed = "gameInstallationStateReadFailed";

    /// <summary>Resource key for <c>gameInstallOrUpdateFailed</c>.</summary>
    public const string GameInstallOrUpdateFailed = "gameInstallOrUpdateFailed";

    /// <summary>Resource key for <c>gameInstallPathNotConfigured</c>.</summary>
    public const string GameInstallPathNotConfigured = "gameInstallPathNotConfigured";

    /// <summary>Resource key for <c>gameIsRunning</c>.</summary>
    public const string GameIsRunning = "gameIsRunning";

    /// <summary>Resource key for <c>gameLaunchedMinimized</c>.</summary>
    public const string GameLaunchedMinimized = "gameLaunchedMinimized";

    /// <summary>Resource key for <c>gameLaunchFailed</c>.</summary>
    public const string GameLaunchFailed = "gameLaunchFailed";

    /// <summary>Resource key for <c>gameManagement</c>.</summary>
    public const string GameManagement = "gameManagement";

    /// <summary>Resource key for <c>gameManagementDescription</c>.</summary>
    public const string GameManagementDescription = "gameManagementDescription";

    /// <summary>Resource key for <c>gameNotInstalled</c>.</summary>
    public const string GameNotInstalled = "gameNotInstalled";

    /// <summary>Resource key for <c>gameOpenFolder</c>.</summary>
    public const string GameOpenFolder = "gameOpenFolder";

    /// <summary>Resource key for <c>gamePath</c>.</summary>
    public const string GamePath = "gamePath";

    /// <summary>Resource key for <c>gamePathMissing</c>.</summary>
    public const string GamePathMissing = "gamePathMissing";

    /// <summary>Resource key for <c>gamePathProtected</c>.</summary>
    public const string GamePathProtected = "gamePathProtected";

    /// <summary>Resource key for <c>gamePathUpdated</c>.</summary>
    public const string GamePathUpdated = "gamePathUpdated";

    /// <summary>Resource key for <c>gamePathUpdateFailed</c>.</summary>
    public const string GamePathUpdateFailed = "gamePathUpdateFailed";

    /// <summary>Resource key for <c>gameProcessStarted</c>.</summary>
    public const string GameProcessStarted = "gameProcessStarted";

    /// <summary>Resource key for <c>gameProcessStartFailed</c>.</summary>
    public const string GameProcessStartFailed = "gameProcessStartFailed";

    /// <summary>Resource key for <c>gameRemoteStateUnavailable</c>.</summary>
    public const string GameRemoteStateUnavailable = "gameRemoteStateUnavailable";

    /// <summary>Resource key for <c>gameRepairFailed</c>.</summary>
    public const string GameRepairFailed = "gameRepairFailed";

    /// <summary>Resource key for <c>gameRuntimePrefixPath</c>.</summary>
    public const string GameRuntimePrefixPath = "gameRuntimePrefixPath";

    /// <summary>Resource key for <c>gameRuntimePrefixPathDescription</c>.</summary>
    public const string GameRuntimePrefixPathDescription = "gameRuntimePrefixPathDescription";

    /// <summary>Resource key for <c>gameRuntimePrefixPathPlaceholder</c>.</summary>
    public const string GameRuntimePrefixPathPlaceholder = "gameRuntimePrefixPathPlaceholder";

    /// <summary>Resource key for <c>gameRuntimeProtonPath</c>.</summary>
    public const string GameRuntimeProtonPath = "gameRuntimeProtonPath";

    /// <summary>Resource key for <c>gameRuntimeProtonPathDescription</c>.</summary>
    public const string GameRuntimeProtonPathDescription = "gameRuntimeProtonPathDescription";

    /// <summary>Resource key for <c>gameRuntimeProtonPathPlaceholder</c>.</summary>
    public const string GameRuntimeProtonPathPlaceholder = "gameRuntimeProtonPathPlaceholder";

    /// <summary>Resource key for <c>gameRuntimeRunner</c>.</summary>
    public const string GameRuntimeRunner = "gameRuntimeRunner";

    /// <summary>Resource key for <c>gameRuntimeRunnerAuto</c>.</summary>
    public const string GameRuntimeRunnerAuto = "gameRuntimeRunnerAuto";

    /// <summary>Resource key for <c>gameRuntimeRunnerDescription</c>.</summary>
    public const string GameRuntimeRunnerDescription = "gameRuntimeRunnerDescription";

    /// <summary>Resource key for <c>gameRuntimeRunnerNative</c>.</summary>
    public const string GameRuntimeRunnerNative = "gameRuntimeRunnerNative";

    /// <summary>Resource key for <c>gameRuntimeRunnerPath</c>.</summary>
    public const string GameRuntimeRunnerPath = "gameRuntimeRunnerPath";

    /// <summary>Resource key for <c>gameRuntimeRunnerPathDescription</c>.</summary>
    public const string GameRuntimeRunnerPathDescription = "gameRuntimeRunnerPathDescription";

    /// <summary>Resource key for <c>gameRuntimeRunnerPathPlaceholder</c>.</summary>
    public const string GameRuntimeRunnerPathPlaceholder = "gameRuntimeRunnerPathPlaceholder";

    /// <summary>Resource key for <c>gameRuntimeRunnerUmu</c>.</summary>
    public const string GameRuntimeRunnerUmu = "gameRuntimeRunnerUmu";

    /// <summary>Resource key for <c>gameRuntimeRunnerWine</c>.</summary>
    public const string GameRuntimeRunnerWine = "gameRuntimeRunnerWine";

    /// <summary>Resource key for <c>gameRuntimeStatusAvailable</c>.</summary>
    public const string GameRuntimeStatusAvailable = "gameRuntimeStatusAvailable";

    /// <summary>Resource key for <c>gameRuntimeStatusBroken</c>.</summary>
    public const string GameRuntimeStatusBroken = "gameRuntimeStatusBroken";

    /// <summary>Resource key for <c>gameRuntimeStatusChecking</c>.</summary>
    public const string GameRuntimeStatusChecking = "gameRuntimeStatusChecking";

    /// <summary>Resource key for <c>gameRuntimeStatusDetailFormat</c>.</summary>
    public const string GameRuntimeStatusDetailFormat = "gameRuntimeStatusDetailFormat";

    /// <summary>Resource key for <c>gameRuntimeStatusEntryDetailFormat</c>.</summary>
    public const string GameRuntimeStatusEntryDetailFormat = "gameRuntimeStatusEntryDetailFormat";

    /// <summary>Resource key for <c>gameRuntimeStatusEntryFormat</c>.</summary>
    public const string GameRuntimeStatusEntryFormat = "gameRuntimeStatusEntryFormat";

    /// <summary>Resource key for <c>gameRuntimeStatusNotFound</c>.</summary>
    public const string GameRuntimeStatusNotFound = "gameRuntimeStatusNotFound";

    /// <summary>Resource key for <c>gameRuntimeStatusTitle</c>.</summary>
    public const string GameRuntimeStatusTitle = "gameRuntimeStatusTitle";

    /// <summary>Resource key for <c>gameRuntimeStatusUnsupported</c>.</summary>
    public const string GameRuntimeStatusUnsupported = "gameRuntimeStatusUnsupported";

    /// <summary>Resource key for <c>gameShortcutCreated</c>.</summary>
    public const string GameShortcutCreated = "gameShortcutCreated";

    /// <summary>Resource key for <c>gameShortcutFailed</c>.</summary>
    public const string GameShortcutFailed = "gameShortcutFailed";

    /// <summary>Resource key for <c>gameShortcutTargetMissing</c>.</summary>
    public const string GameShortcutTargetMissing = "gameShortcutTargetMissing";

    /// <summary>Resource key for <c>gameShortcutUnsupported</c>.</summary>
    public const string GameShortcutUnsupported = "gameShortcutUnsupported";

    /// <summary>Resource key for <c>gitHubReleaseRepository</c>.</summary>
    public const string GitHubReleaseRepository = "gitHubReleaseRepository";

    /// <summary>Resource key for <c>gitHubRepository</c>.</summary>
    public const string GitHubRepository = "gitHubRepository";

    /// <summary>Resource key for <c>helpDocs</c>.</summary>
    public const string HelpDocs = "helpDocs";

    /// <summary>Resource key for <c>installGame</c>.</summary>
    public const string InstallGame = "installGame";

    /// <summary>Resource key for <c>installUpdateCompleted</c>.</summary>
    public const string InstallUpdateCompleted = "installUpdateCompleted";

    /// <summary>Resource key for <c>installUpdateFailedTitle</c>.</summary>
    public const string InstallUpdateFailedTitle = "installUpdateFailedTitle";

    /// <summary>Resource key for <c>issueTracker</c>.</summary>
    public const string IssueTracker = "issueTracker";

    /// <summary>Resource key for <c>keepEditing</c>.</summary>
    public const string KeepEditing = "keepEditing";

    /// <summary>Resource key for <c>language</c>.</summary>
    public const string Language = "language";

    /// <summary>Resource key for <c>languageAuto</c>.</summary>
    public const string LanguageAuto = "languageAuto";

    /// <summary>Resource key for <c>languageDescription</c>.</summary>
    public const string LanguageDescription = "languageDescription";

    /// <summary>Resource key for <c>launchCheck</c>.</summary>
    public const string LaunchCheck = "launchCheck";

    /// <summary>Resource key for <c>launchCheckDescription</c>.</summary>
    public const string LaunchCheckDescription = "launchCheckDescription";

    /// <summary>Resource key for <c>launchCheckLoading</c>.</summary>
    public const string LaunchCheckLoading = "launchCheckLoading";

    /// <summary>Resource key for <c>launchCheckLocalManifest</c>.</summary>
    public const string LaunchCheckLocalManifest = "launchCheckLocalManifest";

    /// <summary>Resource key for <c>launchCheckNone</c>.</summary>
    public const string LaunchCheckNone = "launchCheckNone";

    /// <summary>Resource key for <c>launchCheckRemoteManifest</c>.</summary>
    public const string LaunchCheckRemoteManifest = "launchCheckRemoteManifest";

    /// <summary>Resource key for <c>launchCheckSkipped</c>.</summary>
    public const string LaunchCheckSkipped = "launchCheckSkipped";

    /// <summary>Resource key for <c>launchCheckWithMessage</c>.</summary>
    public const string LaunchCheckWithMessage = "launchCheckWithMessage";

    /// <summary>Resource key for <c>launcherCoreRefreshFailed</c>.</summary>
    public const string LauncherCoreRefreshFailed = "launcherCoreRefreshFailed";

    /// <summary>Resource key for <c>launcherInitFailed</c>.</summary>
    public const string LauncherInitFailed = "launcherInitFailed";

    /// <summary>Resource key for <c>launcherLoadingStatus</c>.</summary>
    public const string LauncherLoadingStatus = "launcherLoadingStatus";

    /// <summary>Resource key for <c>launcherLoadingTitle</c>.</summary>
    public const string LauncherLoadingTitle = "launcherLoadingTitle";

    /// <summary>Resource key for <c>launcherLoadingValue</c>.</summary>
    public const string LauncherLoadingValue = "launcherLoadingValue";

    /// <summary>Resource key for <c>launcherStateNotLoaded</c>.</summary>
    public const string LauncherStateNotLoaded = "launcherStateNotLoaded";

    /// <summary>Resource key for <c>launcherUpdateAvailableMessage</c>.</summary>
    public const string LauncherUpdateAvailableMessage = "launcherUpdateAvailableMessage";

    /// <summary>Resource key for <c>launcherUpdateAvailableTitle</c>.</summary>
    public const string LauncherUpdateAvailableTitle = "launcherUpdateAvailableTitle";

    /// <summary>Resource key for <c>launcherUpdateChannel</c>.</summary>
    public const string LauncherUpdateChannel = "launcherUpdateChannel";

    /// <summary>Resource key for <c>launcherUpdateChannelBeta</c>.</summary>
    public const string LauncherUpdateChannelBeta = "launcherUpdateChannelBeta";

    /// <summary>Resource key for <c>launcherUpdateChannelDescription</c>.</summary>
    public const string LauncherUpdateChannelDescription = "launcherUpdateChannelDescription";

    /// <summary>Resource key for <c>launcherUpdateChannelStable</c>.</summary>
    public const string LauncherUpdateChannelStable = "launcherUpdateChannelStable";

    /// <summary>Resource key for <c>launcherUpdateCheckFailed</c>.</summary>
    public const string LauncherUpdateCheckFailed = "launcherUpdateCheckFailed";

    /// <summary>Resource key for <c>launcherUpdateDownload</c>.</summary>
    public const string LauncherUpdateDownload = "launcherUpdateDownload";

    /// <summary>Resource key for <c>launcherUpdateFileSize</c>.</summary>
    public const string LauncherUpdateFileSize = "launcherUpdateFileSize";

    /// <summary>Resource key for <c>launcherUpdateLater</c>.</summary>
    public const string LauncherUpdateLater = "launcherUpdateLater";

    /// <summary>Resource key for <c>launcherUpdateSelectFile</c>.</summary>
    public const string LauncherUpdateSelectFile = "launcherUpdateSelectFile";

    /// <summary>Resource key for <c>launcherUpdateUpToDate</c>.</summary>
    public const string LauncherUpdateUpToDate = "launcherUpdateUpToDate";

    /// <summary>Resource key for <c>launcherVersionLabel</c>.</summary>
    public const string LauncherVersionLabel = "launcherVersionLabel";

    /// <summary>Resource key for <c>localGameReadError</c>.</summary>
    public const string LocalGameReadError = "localGameReadError";

    /// <summary>Resource key for <c>localManifestMetadataMissing</c>.</summary>
    public const string LocalManifestMetadataMissing = "localManifestMetadataMissing";

    /// <summary>Resource key for <c>localManifestMissing</c>.</summary>
    public const string LocalManifestMissing = "localManifestMissing";

    /// <summary>Resource key for <c>localManifestUnreadable</c>.</summary>
    public const string LocalManifestUnreadable = "localManifestUnreadable";

    /// <summary>Resource key for <c>logExportFailed</c>.</summary>
    public const string LogExportFailed = "logExportFailed";

    /// <summary>Resource key for <c>logExportFolderPickerTitle</c>.</summary>
    public const string LogExportFolderPickerTitle = "logExportFolderPickerTitle";

    /// <summary>Resource key for <c>logExportSucceeded</c>.</summary>
    public const string LogExportSucceeded = "logExportSucceeded";

    /// <summary>Resource key for <c>logFiles</c>.</summary>
    public const string LogFiles = "logFiles";

    /// <summary>Resource key for <c>logFilesDescription</c>.</summary>
    public const string LogFilesDescription = "logFilesDescription";

    /// <summary>Resource key for <c>logFilterAll</c>.</summary>
    public const string LogFilterAll = "logFilterAll";

    /// <summary>Resource key for <c>logFilterDebug</c>.</summary>
    public const string LogFilterDebug = "logFilterDebug";

    /// <summary>Resource key for <c>logFilterError</c>.</summary>
    public const string LogFilterError = "logFilterError";

    /// <summary>Resource key for <c>logFilterFatal</c>.</summary>
    public const string LogFilterFatal = "logFilterFatal";

    /// <summary>Resource key for <c>logFilterInfo</c>.</summary>
    public const string LogFilterInfo = "logFilterInfo";

    /// <summary>Resource key for <c>logFilterVerbose</c>.</summary>
    public const string LogFilterVerbose = "logFilterVerbose";

    /// <summary>Resource key for <c>logFilterWarn</c>.</summary>
    public const string LogFilterWarn = "logFilterWarn";

    /// <summary>Resource key for <c>logLevel</c>.</summary>
    public const string LogLevel = "logLevel";

    /// <summary>Resource key for <c>logLevelDebug</c>.</summary>
    public const string LogLevelDebug = "logLevelDebug";

    /// <summary>Resource key for <c>logLevelDescription</c>.</summary>
    public const string LogLevelDescription = "logLevelDescription";

    /// <summary>Resource key for <c>logLevelError</c>.</summary>
    public const string LogLevelError = "logLevelError";

    /// <summary>Resource key for <c>logLevelFatal</c>.</summary>
    public const string LogLevelFatal = "logLevelFatal";

    /// <summary>Resource key for <c>logLevelInformation</c>.</summary>
    public const string LogLevelInformation = "logLevelInformation";

    /// <summary>Resource key for <c>logLevelVerbose</c>.</summary>
    public const string LogLevelVerbose = "logLevelVerbose";

    /// <summary>Resource key for <c>logLevelWarning</c>.</summary>
    public const string LogLevelWarning = "logLevelWarning";

    /// <summary>Resource key for <c>logLoadEarlier</c>.</summary>
    public const string LogLoadEarlier = "logLoadEarlier";

    /// <summary>Resource key for <c>logLoadFailed</c>.</summary>
    public const string LogLoadFailed = "logLoadFailed";

    /// <summary>Resource key for <c>logNoMatchingEntries</c>.</summary>
    public const string LogNoMatchingEntries = "logNoMatchingEntries";

    /// <summary>Resource key for <c>logSearchPlaceholder</c>.</summary>
    public const string LogSearchPlaceholder = "logSearchPlaceholder";

    /// <summary>Resource key for <c>logViewerTitle</c>.</summary>
    public const string LogViewerTitle = "logViewerTitle";

    /// <summary>Resource key for <c>manifestValidationFailed</c>.</summary>
    public const string ManifestValidationFailed = "manifestValidationFailed";

    /// <summary>Resource key for <c>manifestValidationPassed</c>.</summary>
    public const string ManifestValidationPassed = "manifestValidationPassed";

    /// <summary>Resource key for <c>minimize</c>.</summary>
    public const string Minimize = "minimize";

    /// <summary>Resource key for <c>motionMode</c>.</summary>
    public const string MotionMode = "motionMode";

    /// <summary>Resource key for <c>motionModeDescription</c>.</summary>
    public const string MotionModeDescription = "motionModeDescription";

    /// <summary>Resource key for <c>motionModeFull</c>.</summary>
    public const string MotionModeFull = "motionModeFull";

    /// <summary>Resource key for <c>motionModeReduced</c>.</summary>
    public const string MotionModeReduced = "motionModeReduced";

    /// <summary>Resource key for <c>motionModeSystem</c>.</summary>
    public const string MotionModeSystem = "motionModeSystem";

    /// <summary>Resource key for <c>network</c>.</summary>
    public const string Network = "network";

    /// <summary>Resource key for <c>networkError</c>.</summary>
    public const string NetworkError = "networkError";

    /// <summary>Resource key for <c>networkErrorDetail</c>.</summary>
    public const string NetworkErrorDetail = "networkErrorDetail";

    /// <summary>Resource key for <c>networkLoading</c>.</summary>
    public const string NetworkLoading = "networkLoading";

    /// <summary>Resource key for <c>networkUnavailableTitle</c>.</summary>
    public const string NetworkUnavailableTitle = "networkUnavailableTitle";

    /// <summary>Resource key for <c>networkWithMessage</c>.</summary>
    public const string NetworkWithMessage = "networkWithMessage";

    /// <summary>Resource key for <c>neutralColorStrategy</c>.</summary>
    public const string NeutralColorStrategy = "neutralColorStrategy";

    /// <summary>Resource key for <c>neutralColorStrategyBrandBlue</c>.</summary>
    public const string NeutralColorStrategyBrandBlue = "neutralColorStrategyBrandBlue";

    /// <summary>Resource key for <c>neutralColorStrategyDescription</c>.</summary>
    public const string NeutralColorStrategyDescription = "neutralColorStrategyDescription";

    /// <summary>Resource key for <c>neutralColorStrategySeedFollowing</c>.</summary>
    public const string NeutralColorStrategySeedFollowing = "neutralColorStrategySeedFollowing";

    /// <summary>Resource key for <c>neutralColorStrategySeedFollowingHint</c>.</summary>
    public const string NeutralColorStrategySeedFollowingHint = "neutralColorStrategySeedFollowingHint";

    /// <summary>Resource key for <c>news</c>.</summary>
    public const string News = "news";

    /// <summary>Resource key for <c>nextBanner</c>.</summary>
    public const string NextBanner = "nextBanner";

    /// <summary>Resource key for <c>notice</c>.</summary>
    public const string Notice = "notice";

    /// <summary>Resource key for <c>noticeConfirm</c>.</summary>
    public const string NoticeConfirm = "noticeConfirm";

    /// <summary>Resource key for <c>noticeExit</c>.</summary>
    public const string NoticeExit = "noticeExit";

    /// <summary>Resource key for <c>officialSite</c>.</summary>
    public const string OfficialSite = "officialSite";

    /// <summary>Resource key for <c>openColorPalette</c>.</summary>
    public const string OpenColorPalette = "openColorPalette";

    /// <summary>Resource key for <c>openDataDirectory</c>.</summary>
    public const string OpenDataDirectory = "openDataDirectory";

    /// <summary>Resource key for <c>openDesignGallery</c>.</summary>
    public const string OpenDesignGallery = "openDesignGallery";

    /// <summary>Resource key for <c>operationStopped</c>.</summary>
    public const string OperationStopped = "operationStopped";

    /// <summary>Resource key for <c>operationTelemetryLocal</c>.</summary>
    public const string OperationTelemetryLocal = "operationTelemetryLocal";

    /// <summary>Resource key for <c>operationUnavailableForCurrentState</c>.</summary>
    public const string OperationUnavailableForCurrentState = "operationUnavailableForCurrentState";

    /// <summary>Resource key for <c>path</c>.</summary>
    public const string Path = "path";

    /// <summary>Resource key for <c>pathLoading</c>.</summary>
    public const string PathLoading = "pathLoading";

    /// <summary>Resource key for <c>pause</c>.</summary>
    public const string Pause = "pause";

    /// <summary>Resource key for <c>paused</c>.</summary>
    public const string Paused = "paused";

    /// <summary>Resource key for <c>pauseRequested</c>.</summary>
    public const string PauseRequested = "pauseRequested";

    /// <summary>Resource key for <c>preparing</c>.</summary>
    public const string Preparing = "preparing";

    /// <summary>Resource key for <c>previousBanner</c>.</summary>
    public const string PreviousBanner = "previousBanner";

    /// <summary>Resource key for <c>privacyPolicy</c>.</summary>
    public const string PrivacyPolicy = "privacyPolicy";

    /// <summary>Resource key for <c>proxy</c>.</summary>
    public const string Proxy = "proxy";

    /// <summary>Resource key for <c>proxyAuto</c>.</summary>
    public const string ProxyAuto = "proxyAuto";

    /// <summary>Resource key for <c>proxyDescription</c>.</summary>
    public const string ProxyDescription = "proxyDescription";

    /// <summary>Resource key for <c>proxyDirect</c>.</summary>
    public const string ProxyDirect = "proxyDirect";

    /// <summary>Resource key for <c>proxySystem</c>.</summary>
    public const string ProxySystem = "proxySystem";

    /// <summary>Resource key for <c>ready</c>.</summary>
    public const string Ready = "ready";

    /// <summary>Resource key for <c>readyToUninstall</c>.</summary>
    public const string ReadyToUninstall = "readyToUninstall";

    /// <summary>Resource key for <c>refresh</c>.</summary>
    public const string Refresh = "refresh";

    /// <summary>Resource key for <c>refreshThemeColorPalette</c>.</summary>
    public const string RefreshThemeColorPalette = "refreshThemeColorPalette";

    /// <summary>Resource key for <c>refreshTooltip</c>.</summary>
    public const string RefreshTooltip = "refreshTooltip";

    /// <summary>Resource key for <c>rememberWindowPositionAndSize</c>.</summary>
    public const string RememberWindowPositionAndSize = "rememberWindowPositionAndSize";

    /// <summary>Resource key for <c>rememberWindowPositionAndSizeDescription</c>.</summary>
    public const string RememberWindowPositionAndSizeDescription = "rememberWindowPositionAndSizeDescription";

    /// <summary>Resource key for <c>remoteContentCard</c>.</summary>
    public const string RemoteContentCard = "remoteContentCard";

    /// <summary>Resource key for <c>remoteContentCardDescription</c>.</summary>
    public const string RemoteContentCardDescription = "remoteContentCardDescription";

    /// <summary>Resource key for <c>remoteContentLoadFailed</c>.</summary>
    public const string RemoteContentLoadFailed = "remoteContentLoadFailed";

    /// <summary>Resource key for <c>remoteContentLoading</c>.</summary>
    public const string RemoteContentLoading = "remoteContentLoading";

    /// <summary>Resource key for <c>repair</c>.</summary>
    public const string Repair = "repair";

    /// <summary>Resource key for <c>repairCheckingFiles</c>.</summary>
    public const string RepairCheckingFiles = "repairCheckingFiles";

    /// <summary>Resource key for <c>repairCompleted</c>.</summary>
    public const string RepairCompleted = "repairCompleted";

    /// <summary>Resource key for <c>repairConfirm</c>.</summary>
    public const string RepairConfirm = "repairConfirm";

    /// <summary>Resource key for <c>repairConfirmDescription</c>.</summary>
    public const string RepairConfirmDescription = "repairConfirmDescription";

    /// <summary>Resource key for <c>repairFilesNeeded</c>.</summary>
    public const string RepairFilesNeeded = "repairFilesNeeded";

    /// <summary>Resource key for <c>repairing</c>.</summary>
    public const string Repairing = "repairing";

    /// <summary>Resource key for <c>repairNoChanges</c>.</summary>
    public const string RepairNoChanges = "repairNoChanges";

    /// <summary>Resource key for <c>repairNoFilesNeeded</c>.</summary>
    public const string RepairNoFilesNeeded = "repairNoFilesNeeded";

    /// <summary>Resource key for <c>repairWarning</c>.</summary>
    public const string RepairWarning = "repairWarning";

    /// <summary>Resource key for <c>resourcePanel</c>.</summary>
    public const string ResourcePanel = "resourcePanel";

    /// <summary>Resource key for <c>resourcePanelCafeOnlyDescription</c>.</summary>
    public const string ResourcePanelCafeOnlyDescription = "resourcePanelCafeOnlyDescription";

    /// <summary>Resource key for <c>resourcePanelCafeOnlyMessage</c>.</summary>
    public const string ResourcePanelCafeOnlyMessage = "resourcePanelCafeOnlyMessage";

    /// <summary>Resource key for <c>resourcePanelCafeOnlySwitch</c>.</summary>
    public const string ResourcePanelCafeOnlySwitch = "resourcePanelCafeOnlySwitch";

    /// <summary>Resource key for <c>resourcePanelCafeOnlyTitle</c>.</summary>
    public const string ResourcePanelCafeOnlyTitle = "resourcePanelCafeOnlyTitle";

    /// <summary>Resource key for <c>resourcePanelChangeUid</c>.</summary>
    public const string ResourcePanelChangeUid = "resourcePanelChangeUid";

    /// <summary>Resource key for <c>resourcePanelCurrentUid</c>.</summary>
    public const string ResourcePanelCurrentUid = "resourcePanelCurrentUid";

    /// <summary>Resource key for <c>resourcePanelDescription</c>.</summary>
    public const string ResourcePanelDescription = "resourcePanelDescription";

    /// <summary>Resource key for <c>resourcePanelEditUid</c>.</summary>
    public const string ResourcePanelEditUid = "resourcePanelEditUid";

    /// <summary>Resource key for <c>resourcePanelFailed</c>.</summary>
    public const string ResourcePanelFailed = "resourcePanelFailed";

    /// <summary>Resource key for <c>resourcePanelGameText</c>.</summary>
    public const string ResourcePanelGameText = "resourcePanelGameText";

    /// <summary>Resource key for <c>resourcePanelLoadFailed</c>.</summary>
    public const string ResourcePanelLoadFailed = "resourcePanelLoadFailed";

    /// <summary>Resource key for <c>resourcePanelLoading</c>.</summary>
    public const string ResourcePanelLoading = "resourcePanelLoading";

    /// <summary>Resource key for <c>resourcePanelLocalizedVersion</c>.</summary>
    public const string ResourcePanelLocalizedVersion = "resourcePanelLocalizedVersion";

    /// <summary>Resource key for <c>resourcePanelMainVoice</c>.</summary>
    public const string ResourcePanelMainVoice = "resourcePanelMainVoice";

    /// <summary>Resource key for <c>resourcePanelManualUid</c>.</summary>
    public const string ResourcePanelManualUid = "resourcePanelManualUid";

    /// <summary>Resource key for <c>resourcePanelMedia</c>.</summary>
    public const string ResourcePanelMedia = "resourcePanelMedia";

    /// <summary>Resource key for <c>resourcePanelOfficialVersion</c>.</summary>
    public const string ResourcePanelOfficialVersion = "resourcePanelOfficialVersion";

    /// <summary>Resource key for <c>resourcePanelReady</c>.</summary>
    public const string ResourcePanelReady = "resourcePanelReady";

    /// <summary>Resource key for <c>resourcePanelRefresh</c>.</summary>
    public const string ResourcePanelRefresh = "resourcePanelRefresh";

    /// <summary>Resource key for <c>resourcePanelSave</c>.</summary>
    public const string ResourcePanelSave = "resourcePanelSave";

    /// <summary>Resource key for <c>resourcePanelSaved</c>.</summary>
    public const string ResourcePanelSaved = "resourcePanelSaved";

    /// <summary>Resource key for <c>resourcePanelSaveFailed</c>.</summary>
    public const string ResourcePanelSaveFailed = "resourcePanelSaveFailed";

    /// <summary>Resource key for <c>resourcePanelSaveUid</c>.</summary>
    public const string ResourcePanelSaveUid = "resourcePanelSaveUid";

    /// <summary>Resource key for <c>resourcePanelUid</c>.</summary>
    public const string ResourcePanelUid = "resourcePanelUid";

    /// <summary>Resource key for <c>resourcePanelUidEmpty</c>.</summary>
    public const string ResourcePanelUidEmpty = "resourcePanelUidEmpty";

    /// <summary>Resource key for <c>resourcePanelUidInvalidFormat</c>.</summary>
    public const string ResourcePanelUidInvalidFormat = "resourcePanelUidInvalidFormat";

    /// <summary>Resource key for <c>resourcePanelUidMissing</c>.</summary>
    public const string ResourcePanelUidMissing = "resourcePanelUidMissing";

    /// <summary>Resource key for <c>resourcePanelUidSaved</c>.</summary>
    public const string ResourcePanelUidSaved = "resourcePanelUidSaved";

    /// <summary>Resource key for <c>resourcePanelUidSource</c>.</summary>
    public const string ResourcePanelUidSource = "resourcePanelUidSource";

    /// <summary>Resource key for <c>resourcePanelUidSourceAuto</c>.</summary>
    public const string ResourcePanelUidSourceAuto = "resourcePanelUidSourceAuto";

    /// <summary>Resource key for <c>resourcePanelUidSourceCustom</c>.</summary>
    public const string ResourcePanelUidSourceCustom = "resourcePanelUidSourceCustom";

    /// <summary>Resource key for <c>resourcePanelWaiting</c>.</summary>
    public const string ResourcePanelWaiting = "resourcePanelWaiting";

    /// <summary>Resource key for <c>resume</c>.</summary>
    public const string Resume = "resume";

    /// <summary>Resource key for <c>resumeRequested</c>.</summary>
    public const string ResumeRequested = "resumeRequested";

    /// <summary>Resource key for <c>retry</c>.</summary>
    public const string Retry = "retry";

    /// <summary>Resource key for <c>runningLaunchCheck</c>.</summary>
    public const string RunningLaunchCheck = "runningLaunchCheck";

    /// <summary>Resource key for <c>save</c>.</summary>
    public const string Save = "save";

    /// <summary>Resource key for <c>selectInstalledGame</c>.</summary>
    public const string SelectInstalledGame = "selectInstalledGame";

    /// <summary>Resource key for <c>settings</c>.</summary>
    public const string Settings = "settings";

    /// <summary>Resource key for <c>settingsCategoryAbout</c>.</summary>
    public const string SettingsCategoryAbout = "settingsCategoryAbout";

    /// <summary>Resource key for <c>settingsCategoryAboutDescription</c>.</summary>
    public const string SettingsCategoryAboutDescription = "settingsCategoryAboutDescription";

    /// <summary>Resource key for <c>settingsCategoryAdvanced</c>.</summary>
    public const string SettingsCategoryAdvanced = "settingsCategoryAdvanced";

    /// <summary>Resource key for <c>settingsCategoryAdvancedDescription</c>.</summary>
    public const string SettingsCategoryAdvancedDescription = "settingsCategoryAdvancedDescription";

    /// <summary>Resource key for <c>settingsCategoryAppearance</c>.</summary>
    public const string SettingsCategoryAppearance = "settingsCategoryAppearance";

    /// <summary>Resource key for <c>settingsCategoryAppearanceDescription</c>.</summary>
    public const string SettingsCategoryAppearanceDescription = "settingsCategoryAppearanceDescription";

    /// <summary>Resource key for <c>settingsCategoryDownloadNetwork</c>.</summary>
    public const string SettingsCategoryDownloadNetwork = "settingsCategoryDownloadNetwork";

    /// <summary>Resource key for <c>settingsCategoryDownloadNetworkDescription</c>.</summary>
    public const string SettingsCategoryDownloadNetworkDescription = "settingsCategoryDownloadNetworkDescription";

    /// <summary>Resource key for <c>settingsCategoryGame</c>.</summary>
    public const string SettingsCategoryGame = "settingsCategoryGame";

    /// <summary>Resource key for <c>settingsCategoryGameDescription</c>.</summary>
    public const string SettingsCategoryGameDescription = "settingsCategoryGameDescription";

    /// <summary>Resource key for <c>settingsCategoryGeneral</c>.</summary>
    public const string SettingsCategoryGeneral = "settingsCategoryGeneral";

    /// <summary>Resource key for <c>settingsCategoryGeneralDescription</c>.</summary>
    public const string SettingsCategoryGeneralDescription = "settingsCategoryGeneralDescription";

    /// <summary>Resource key for <c>settingsCategoryNotificationsContent</c>.</summary>
    public const string SettingsCategoryNotificationsContent = "settingsCategoryNotificationsContent";

    /// <summary>Resource key for <c>settingsCategoryNotificationsContentDescription</c>.</summary>
    public const string SettingsCategoryNotificationsContentDescription = "settingsCategoryNotificationsContentDescription";

    /// <summary>Resource key for <c>settingsGroupAboutActions</c>.</summary>
    public const string SettingsGroupAboutActions = "settingsGroupAboutActions";

    /// <summary>Resource key for <c>settingsGroupAppPreferences</c>.</summary>
    public const string SettingsGroupAppPreferences = "settingsGroupAppPreferences";

    /// <summary>Resource key for <c>settingsGroupBackground</c>.</summary>
    public const string SettingsGroupBackground = "settingsGroupBackground";

    /// <summary>Resource key for <c>settingsGroupConnection</c>.</summary>
    public const string SettingsGroupConnection = "settingsGroupConnection";

    /// <summary>Resource key for <c>settingsGroupDiagnostics</c>.</summary>
    public const string SettingsGroupDiagnostics = "settingsGroupDiagnostics";

    /// <summary>Resource key for <c>settingsGroupDisplay</c>.</summary>
    public const string SettingsGroupDisplay = "settingsGroupDisplay";

    /// <summary>Resource key for <c>settingsGroupGameFiles</c>.</summary>
    public const string SettingsGroupGameFiles = "settingsGroupGameFiles";

    /// <summary>Resource key for <c>settingsGroupGameRuntime</c>.</summary>
    public const string SettingsGroupGameRuntime = "settingsGroupGameRuntime";

    /// <summary>Resource key for <c>settingsGroupThemeColor</c>.</summary>
    public const string SettingsGroupThemeColor = "settingsGroupThemeColor";

    /// <summary>Resource key for <c>settingsSaved</c>.</summary>
    public const string SettingsSaved = "settingsSaved";

    /// <summary>Resource key for <c>settingsSaveFailed</c>.</summary>
    public const string SettingsSaveFailed = "settingsSaveFailed";

    /// <summary>Resource key for <c>settingsSummaryWithTheme</c>.</summary>
    public const string SettingsSummaryWithTheme = "settingsSummaryWithTheme";

    /// <summary>Resource key for <c>setupWizardBrowse</c>.</summary>
    public const string SetupWizardBrowse = "setupWizardBrowse";

    /// <summary>Resource key for <c>setupWizardDownloadSource</c>.</summary>
    public const string SetupWizardDownloadSource = "setupWizardDownloadSource";

    /// <summary>Resource key for <c>setupWizardDownloadSourceCafeDescription</c>.</summary>
    public const string SetupWizardDownloadSourceCafeDescription = "setupWizardDownloadSourceCafeDescription";

    /// <summary>Resource key for <c>setupWizardDownloadSourceCafeRecommendationLabel</c>.</summary>
    public const string SetupWizardDownloadSourceCafeRecommendationLabel = "setupWizardDownloadSourceCafeRecommendationLabel";

    /// <summary>Resource key for <c>setupWizardDownloadSourceCafeRecommendationReason</c>.</summary>
    public const string SetupWizardDownloadSourceCafeRecommendationReason = "setupWizardDownloadSourceCafeRecommendationReason";

    /// <summary>Resource key for <c>setupWizardDownloadSourceHint</c>.</summary>
    public const string SetupWizardDownloadSourceHint = "setupWizardDownloadSourceHint";

    /// <summary>Resource key for <c>setupWizardDownloadSourceOfficialDescription</c>.</summary>
    public const string SetupWizardDownloadSourceOfficialDescription = "setupWizardDownloadSourceOfficialDescription";

    /// <summary>Resource key for <c>setupWizardEditStep</c>.</summary>
    public const string SetupWizardEditStep = "setupWizardEditStep";

    /// <summary>Resource key for <c>setupWizardExitConfirm</c>.</summary>
    public const string SetupWizardExitConfirm = "setupWizardExitConfirm";

    /// <summary>Resource key for <c>setupWizardExitMessage</c>.</summary>
    public const string SetupWizardExitMessage = "setupWizardExitMessage";

    /// <summary>Resource key for <c>setupWizardExitTitle</c>.</summary>
    public const string SetupWizardExitTitle = "setupWizardExitTitle";

    /// <summary>Resource key for <c>setupWizardFinish</c>.</summary>
    public const string SetupWizardFinish = "setupWizardFinish";

    /// <summary>Resource key for <c>setupWizardGamePath</c>.</summary>
    public const string SetupWizardGamePath = "setupWizardGamePath";

    /// <summary>Resource key for <c>setupWizardGamePathAvailable</c>.</summary>
    public const string SetupWizardGamePathAvailable = "setupWizardGamePathAvailable";

    /// <summary>Resource key for <c>setupWizardGamePathChecking</c>.</summary>
    public const string SetupWizardGamePathChecking = "setupWizardGamePathChecking";

    /// <summary>Resource key for <c>setupWizardGamePathCorrupted</c>.</summary>
    public const string SetupWizardGamePathCorrupted = "setupWizardGamePathCorrupted";

    /// <summary>Resource key for <c>setupWizardGamePathEmpty</c>.</summary>
    public const string SetupWizardGamePathEmpty = "setupWizardGamePathEmpty";

    /// <summary>Resource key for <c>setupWizardGamePathHint</c>.</summary>
    public const string SetupWizardGamePathHint = "setupWizardGamePathHint";

    /// <summary>Resource key for <c>setupWizardGamePathInaccessible</c>.</summary>
    public const string SetupWizardGamePathInaccessible = "setupWizardGamePathInaccessible";

    /// <summary>Resource key for <c>setupWizardGamePathInstalled</c>.</summary>
    public const string SetupWizardGamePathInstalled = "setupWizardGamePathInstalled";

    /// <summary>Resource key for <c>setupWizardGamePathStatusDescription</c>.</summary>
    public const string SetupWizardGamePathStatusDescription = "setupWizardGamePathStatusDescription";

    /// <summary>Resource key for <c>setupWizardGamePathStatusTitle</c>.</summary>
    public const string SetupWizardGamePathStatusTitle = "setupWizardGamePathStatusTitle";

    /// <summary>Resource key for <c>setupWizardLanguage</c>.</summary>
    public const string SetupWizardLanguage = "setupWizardLanguage";

    /// <summary>Resource key for <c>setupWizardLanguageHint</c>.</summary>
    public const string SetupWizardLanguageHint = "setupWizardLanguageHint";

    /// <summary>Resource key for <c>setupWizardNext</c>.</summary>
    public const string SetupWizardNext = "setupWizardNext";

    /// <summary>Resource key for <c>setupWizardPrevious</c>.</summary>
    public const string SetupWizardPrevious = "setupWizardPrevious";

    /// <summary>Resource key for <c>setupWizardProxy</c>.</summary>
    public const string SetupWizardProxy = "setupWizardProxy";

    /// <summary>Resource key for <c>setupWizardProxyAutoDescription</c>.</summary>
    public const string SetupWizardProxyAutoDescription = "setupWizardProxyAutoDescription";

    /// <summary>Resource key for <c>setupWizardProxyDirectDescription</c>.</summary>
    public const string SetupWizardProxyDirectDescription = "setupWizardProxyDirectDescription";

    /// <summary>Resource key for <c>setupWizardProxyHint</c>.</summary>
    public const string SetupWizardProxyHint = "setupWizardProxyHint";

    /// <summary>Resource key for <c>setupWizardProxySystemDescription</c>.</summary>
    public const string SetupWizardProxySystemDescription = "setupWizardProxySystemDescription";

    /// <summary>Resource key for <c>setupWizardReview</c>.</summary>
    public const string SetupWizardReview = "setupWizardReview";

    /// <summary>Resource key for <c>setupWizardReviewHint</c>.</summary>
    public const string SetupWizardReviewHint = "setupWizardReviewHint";

    /// <summary>Resource key for <c>setupWizardSkip</c>.</summary>
    public const string SetupWizardSkip = "setupWizardSkip";

    /// <summary>Resource key for <c>setupWizardStep0Title</c>.</summary>
    public const string SetupWizardStep0Title = "setupWizardStep0Title";

    /// <summary>Resource key for <c>setupWizardStep1Title</c>.</summary>
    public const string SetupWizardStep1Title = "setupWizardStep1Title";

    /// <summary>Resource key for <c>setupWizardStep2Title</c>.</summary>
    public const string SetupWizardStep2Title = "setupWizardStep2Title";

    /// <summary>Resource key for <c>setupWizardStep3Title</c>.</summary>
    public const string SetupWizardStep3Title = "setupWizardStep3Title";

    /// <summary>Resource key for <c>setupWizardStep4Title</c>.</summary>
    public const string SetupWizardStep4Title = "setupWizardStep4Title";

    /// <summary>Resource key for <c>setupWizardStepTitle</c>.</summary>
    public const string SetupWizardStepTitle = "setupWizardStepTitle";

    /// <summary>Resource key for <c>setupWizardWelcomeText</c>.</summary>
    public const string SetupWizardWelcomeText = "setupWizardWelcomeText";

    /// <summary>Resource key for <c>setupWizardWelcomeTitle</c>.</summary>
    public const string SetupWizardWelcomeTitle = "setupWizardWelcomeTitle";

    /// <summary>Resource key for <c>showLauncher</c>.</summary>
    public const string ShowLauncher = "showLauncher";

    /// <summary>Resource key for <c>showRemoteContentCard</c>.</summary>
    public const string ShowRemoteContentCard = "showRemoteContentCard";

    /// <summary>Resource key for <c>socialMedia</c>.</summary>
    public const string SocialMedia = "socialMedia";

    /// <summary>Resource key for <c>speed10MBs</c>.</summary>
    public const string Speed10MBs = "speed10MBs";

    /// <summary>Resource key for <c>speed1MBs</c>.</summary>
    public const string Speed1MBs = "speed1MBs";

    /// <summary>Resource key for <c>speed25MBs</c>.</summary>
    public const string Speed25MBs = "speed25MBs";

    /// <summary>Resource key for <c>speed50MBs</c>.</summary>
    public const string Speed50MBs = "speed50MBs";

    /// <summary>Resource key for <c>speed5MBs</c>.</summary>
    public const string Speed5MBs = "speed5MBs";

    /// <summary>Resource key for <c>speedUnlimited</c>.</summary>
    public const string SpeedUnlimited = "speedUnlimited";

    /// <summary>Resource key for <c>startGame</c>.</summary>
    public const string StartGame = "startGame";

    /// <summary>Resource key for <c>startupUpdateAvailable</c>.</summary>
    public const string StartupUpdateAvailable = "startupUpdateAvailable";

    /// <summary>Resource key for <c>statusDetailMode</c>.</summary>
    public const string StatusDetailMode = "statusDetailMode";

    /// <summary>Resource key for <c>statusDetailModeCompact</c>.</summary>
    public const string StatusDetailModeCompact = "statusDetailModeCompact";

    /// <summary>Resource key for <c>statusDetailModeDescription</c>.</summary>
    public const string StatusDetailModeDescription = "statusDetailModeDescription";

    /// <summary>Resource key for <c>statusDetailModeHidden</c>.</summary>
    public const string StatusDetailModeHidden = "statusDetailModeHidden";

    /// <summary>Resource key for <c>statusLaunchCheckLocal</c>.</summary>
    public const string StatusLaunchCheckLocal = "statusLaunchCheckLocal";

    /// <summary>Resource key for <c>statusLaunchCheckNone</c>.</summary>
    public const string StatusLaunchCheckNone = "statusLaunchCheckNone";

    /// <summary>Resource key for <c>statusLaunchCheckRemote</c>.</summary>
    public const string StatusLaunchCheckRemote = "statusLaunchCheckRemote";

    /// <summary>Resource key for <c>statusNetworkLoaded</c>.</summary>
    public const string StatusNetworkLoaded = "statusNetworkLoaded";

    /// <summary>Resource key for <c>stop</c>.</summary>
    public const string Stop = "stop";

    /// <summary>Resource key for <c>stopDownloadMessage</c>.</summary>
    public const string StopDownloadMessage = "stopDownloadMessage";

    /// <summary>Resource key for <c>stopDownloadTitle</c>.</summary>
    public const string StopDownloadTitle = "stopDownloadTitle";

    /// <summary>Resource key for <c>stopRequested</c>.</summary>
    public const string StopRequested = "stopRequested";

    /// <summary>Resource key for <c>theme</c>.</summary>
    public const string Theme = "theme";

    /// <summary>Resource key for <c>themeColor</c>.</summary>
    public const string ThemeColor = "themeColor";

    /// <summary>Resource key for <c>themeColorCustom</c>.</summary>
    public const string ThemeColorCustom = "themeColorCustom";

    /// <summary>Resource key for <c>themeColorDefault</c>.</summary>
    public const string ThemeColorDefault = "themeColorDefault";

    /// <summary>Resource key for <c>themeColorDescription</c>.</summary>
    public const string ThemeColorDescription = "themeColorDescription";

    /// <summary>Resource key for <c>themeColorExtractionAlgorithm</c>.</summary>
    public const string ThemeColorExtractionAlgorithm = "themeColorExtractionAlgorithm";

    /// <summary>Resource key for <c>themeColorExtractionAlgorithmCelebiScore</c>.</summary>
    public const string ThemeColorExtractionAlgorithmCelebiScore = "themeColorExtractionAlgorithmCelebiScore";

    /// <summary>Resource key for <c>themeColorExtractionAlgorithmDescription</c>.</summary>
    public const string ThemeColorExtractionAlgorithmDescription = "themeColorExtractionAlgorithmDescription";

    /// <summary>Resource key for <c>themeColorExtractionAlgorithmOctree</c>.</summary>
    public const string ThemeColorExtractionAlgorithmOctree = "themeColorExtractionAlgorithmOctree";

    /// <summary>Resource key for <c>themeColorExtractionAlgorithmWsmeans</c>.</summary>
    public const string ThemeColorExtractionAlgorithmWsmeans = "themeColorExtractionAlgorithmWsmeans";

    /// <summary>Resource key for <c>themeColorExtractionAlgorithmWu</c>.</summary>
    public const string ThemeColorExtractionAlgorithmWu = "themeColorExtractionAlgorithmWu";

    /// <summary>Resource key for <c>themeColorPalette</c>.</summary>
    public const string ThemeColorPalette = "themeColorPalette";

    /// <summary>Resource key for <c>themeColorPaletteDescription</c>.</summary>
    public const string ThemeColorPaletteDescription = "themeColorPaletteDescription";

    /// <summary>Resource key for <c>themeColorSystem</c>.</summary>
    public const string ThemeColorSystem = "themeColorSystem";

    /// <summary>Resource key for <c>themeColorVariant</c>.</summary>
    public const string ThemeColorVariant = "themeColorVariant";

    /// <summary>Resource key for <c>themeColorVariantContent</c>.</summary>
    public const string ThemeColorVariantContent = "themeColorVariantContent";

    /// <summary>Resource key for <c>themeColorVariantDescription</c>.</summary>
    public const string ThemeColorVariantDescription = "themeColorVariantDescription";

    /// <summary>Resource key for <c>themeColorVariantExpressive</c>.</summary>
    public const string ThemeColorVariantExpressive = "themeColorVariantExpressive";

    /// <summary>Resource key for <c>themeColorVariantFidelity</c>.</summary>
    public const string ThemeColorVariantFidelity = "themeColorVariantFidelity";

    /// <summary>Resource key for <c>themeColorVariantMonochrome</c>.</summary>
    public const string ThemeColorVariantMonochrome = "themeColorVariantMonochrome";

    /// <summary>Resource key for <c>themeColorVariantNeutral</c>.</summary>
    public const string ThemeColorVariantNeutral = "themeColorVariantNeutral";

    /// <summary>Resource key for <c>themeColorVariantRainbow</c>.</summary>
    public const string ThemeColorVariantRainbow = "themeColorVariantRainbow";

    /// <summary>Resource key for <c>themeColorVariantTonalSpot</c>.</summary>
    public const string ThemeColorVariantTonalSpot = "themeColorVariantTonalSpot";

    /// <summary>Resource key for <c>themeColorVariantVibrant</c>.</summary>
    public const string ThemeColorVariantVibrant = "themeColorVariantVibrant";

    /// <summary>Resource key for <c>themeColorWallpaper</c>.</summary>
    public const string ThemeColorWallpaper = "themeColorWallpaper";

    /// <summary>Resource key for <c>themeDark</c>.</summary>
    public const string ThemeDark = "themeDark";

    /// <summary>Resource key for <c>themeDescription</c>.</summary>
    public const string ThemeDescription = "themeDescription";

    /// <summary>Resource key for <c>themeLight</c>.</summary>
    public const string ThemeLight = "themeLight";

    /// <summary>Resource key for <c>themeSystem</c>.</summary>
    public const string ThemeSystem = "themeSystem";

    /// <summary>Resource key for <c>toastActionFailedMessage</c>.</summary>
    public const string ToastActionFailedMessage = "toastActionFailedMessage";

    /// <summary>Resource key for <c>toastActionFailedTitle</c>.</summary>
    public const string ToastActionFailedTitle = "toastActionFailedTitle";

    /// <summary>Resource key for <c>toastError</c>.</summary>
    public const string ToastError = "toastError";

    /// <summary>Resource key for <c>toastInfo</c>.</summary>
    public const string ToastInfo = "toastInfo";

    /// <summary>Resource key for <c>toastRegionName</c>.</summary>
    public const string ToastRegionName = "toastRegionName";

    /// <summary>Resource key for <c>toastSuccess</c>.</summary>
    public const string ToastSuccess = "toastSuccess";

    /// <summary>Resource key for <c>toastWarning</c>.</summary>
    public const string ToastWarning = "toastWarning";

    /// <summary>Resource key for <c>toggleOff</c>.</summary>
    public const string ToggleOff = "toggleOff";

    /// <summary>Resource key for <c>toggleOn</c>.</summary>
    public const string ToggleOn = "toggleOn";

    /// <summary>Resource key for <c>trayExitLauncher</c>.</summary>
    public const string TrayExitLauncher = "trayExitLauncher";

    /// <summary>Resource key for <c>trayOpenLauncher</c>.</summary>
    public const string TrayOpenLauncher = "trayOpenLauncher";

    /// <summary>Resource key for <c>unexpectedError</c>.</summary>
    public const string UnexpectedError = "unexpectedError";

    /// <summary>Resource key for <c>uninstall</c>.</summary>
    public const string Uninstall = "uninstall";

    /// <summary>Resource key for <c>uninstallCompleted</c>.</summary>
    public const string UninstallCompleted = "uninstallCompleted";

    /// <summary>Resource key for <c>uninstallConfirmDescription</c>.</summary>
    public const string UninstallConfirmDescription = "uninstallConfirmDescription";

    /// <summary>Resource key for <c>uninstallConfirmText</c>.</summary>
    public const string UninstallConfirmText = "uninstallConfirmText";

    /// <summary>Resource key for <c>uninstallFailed</c>.</summary>
    public const string UninstallFailed = "uninstallFailed";

    /// <summary>Resource key for <c>uninstalling</c>.</summary>
    public const string Uninstalling = "uninstalling";

    /// <summary>Resource key for <c>unknown</c>.</summary>
    public const string Unknown = "unknown";

    /// <summary>Resource key for <c>unsavedChanges</c>.</summary>
    public const string UnsavedChanges = "unsavedChanges";

    /// <summary>Resource key for <c>unsavedChangesMessage</c>.</summary>
    public const string UnsavedChangesMessage = "unsavedChangesMessage";

    /// <summary>Resource key for <c>updateAvailable</c>.</summary>
    public const string UpdateAvailable = "updateAvailable";

    /// <summary>Resource key for <c>updateCheckingFiles</c>.</summary>
    public const string UpdateCheckingFiles = "updateCheckingFiles";

    /// <summary>Resource key for <c>updateGame</c>.</summary>
    public const string UpdateGame = "updateGame";

    /// <summary>Resource key for <c>updateRequired</c>.</summary>
    public const string UpdateRequired = "updateRequired";

    /// <summary>Resource key for <c>verificationFailed</c>.</summary>
    public const string VerificationFailed = "verificationFailed";

    /// <summary>Resource key for <c>verificationRetry</c>.</summary>
    public const string VerificationRetry = "verificationRetry";

    /// <summary>Resource key for <c>verifyingDownloadedFiles</c>.</summary>
    public const string VerifyingDownloadedFiles = "verifyingDownloadedFiles";

    /// <summary>Resource key for <c>version</c>.</summary>
    public const string Version = "version";

    /// <summary>Resource key for <c>versionInfo</c>.</summary>
    public const string VersionInfo = "versionInfo";

    /// <summary>Resource key for <c>versionInstalled</c>.</summary>
    public const string VersionInstalled = "versionInstalled";

    /// <summary>Resource key for <c>versionLatest</c>.</summary>
    public const string VersionLatest = "versionLatest";

    /// <summary>Resource key for <c>versionLoading</c>.</summary>
    public const string VersionLoading = "versionLoading";

    /// <summary>Resource key for <c>versionUnavailable</c>.</summary>
    public const string VersionUnavailable = "versionUnavailable";

    /// <summary>Resource key for <c>viewLog</c>.</summary>
    public const string ViewLog = "viewLog";

    /// <summary>Resource key for <c>working</c>.</summary>
    public const string Working = "working";
}
