#nullable enable

namespace Cafe.Launcher.Avalonia.Resources;

using System.Globalization;
using System.Resources;

/// <summary>
/// Strongly typed accessors for <c>LauncherStrings.resx</c>.
/// Generated by scripts/Generate-LauncherStringsDesigner.ps1; do not edit by hand.
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("scripts/Generate-LauncherStringsDesigner.ps1", "1.0.0.0")]
[System.Diagnostics.DebuggerNonUserCodeAttribute]
internal static class LauncherStrings
{
    private static ResourceManager? resourceMan;

    internal static ResourceManager ResourceManager =>
        resourceMan ??= new ResourceManager(
            "Cafe.Launcher.Avalonia.Resources.LauncherStrings",
            typeof(LauncherStrings).Assembly);

    private static string GetRequiredString(string key) =>
        ResourceManager.GetString(key, CultureInfo.CurrentUICulture)
        ?? throw new MissingManifestResourceException($"Resource key '{key}' was not found.");

    internal static string About => GetRequiredString("about");

    internal static string AboutActionsGeneral => GetRequiredString("aboutActionsGeneral");

    internal static string AboutCopyrightText => GetRequiredString("aboutCopyrightText");

    internal static string AboutDescription => GetRequiredString("aboutDescription");

    internal static string AboutDisclaimerText => GetRequiredString("aboutDisclaimerText");

    internal static string AboutLinks => GetRequiredString("aboutLinks");

    internal static string ApiFailedNoFileChange => GetRequiredString("apiFailedNoFileChange");

    internal static string AppearancePreviewFailed => GetRequiredString("appearancePreviewFailed");

    internal static string BackgroundFillColor => GetRequiredString("backgroundFillColor");

    internal static string BackgroundFillColorDescription => GetRequiredString("backgroundFillColorDescription");

    internal static string BackgroundFit => GetRequiredString("backgroundFit");

    internal static string BackgroundFitDescription => GetRequiredString("backgroundFitDescription");

    internal static string BackgroundFitFill => GetRequiredString("backgroundFitFill");

    internal static string BackgroundFitUniform => GetRequiredString("backgroundFitUniform");

    internal static string BackgroundFitUniformToFill => GetRequiredString("backgroundFitUniformToFill");

    internal static string BackgroundSource => GetRequiredString("backgroundSource");

    internal static string BackgroundSourceBundled => GetRequiredString("backgroundSourceBundled");

    internal static string BackgroundSourceCustom => GetRequiredString("backgroundSourceCustom");

    internal static string BackgroundSourceDescription => GetRequiredString("backgroundSourceDescription");

    internal static string BackgroundSourceRemote => GetRequiredString("backgroundSourceRemote");

    internal static string Banner => GetRequiredString("banner");

    internal static string BannerLoading => GetRequiredString("bannerLoading");

    internal static string BannerLoadingFailed => GetRequiredString("bannerLoadingFailed");

    internal static string Banners => GetRequiredString("banners");

    internal static string BuildConfigurationLabel => GetRequiredString("buildConfigurationLabel");

    internal static string BuildInfo => GetRequiredString("buildInfo");

    internal static string BuildingFileList => GetRequiredString("buildingFileList");

    internal static string BuildTimeLabel => GetRequiredString("buildTimeLabel");

    internal static string Busy => GetRequiredString("busy");

    internal static string Cancel => GetRequiredString("cancel");

    internal static string CarouselPage => GetRequiredString("carouselPage");

    internal static string CdnConfigIncomplete => GetRequiredString("cdnConfigIncomplete");

    internal static string ChangePath => GetRequiredString("changePath");

    internal static string CheckUpdates => GetRequiredString("checkUpdates");

    internal static string Choose => GetRequiredString("choose");

    internal static string ChooseBackgroundFolderTitle => GetRequiredString("chooseBackgroundFolderTitle");

    internal static string ChooseBackgroundImageTitle => GetRequiredString("chooseBackgroundImageTitle");

    internal static string ChooseFolder => GetRequiredString("chooseFolder");

    internal static string ChooseImage => GetRequiredString("chooseImage");

    internal static string ChooseInstallFolder => GetRequiredString("chooseInstallFolder");

    internal static string ChoosePathInstall => GetRequiredString("choosePathInstall");

    internal static string ClearBackground => GetRequiredString("clearBackground");

    internal static string Close => GetRequiredString("close");

    internal static string CloseBehavior => GetRequiredString("closeBehavior");

    internal static string CloseBehaviorDescription => GetRequiredString("closeBehaviorDescription");

    internal static string CloseBehaviorExit => GetRequiredString("closeBehaviorExit");

    internal static string CloseBehaviorMinimize => GetRequiredString("closeBehaviorMinimize");

    internal static string CommitLabel => GetRequiredString("commitLabel");

    internal static string ConfirmUninstall => GetRequiredString("confirmUninstall");

    internal static string ConnectingApi => GetRequiredString("connectingApi");

    internal static string ContactCustomerSupport => GetRequiredString("contactCustomerSupport");

    internal static string Copyright => GetRequiredString("copyright");

    internal static string CustomBackground => GetRequiredString("customBackground");

    internal static string CustomBackgroundDescription => GetRequiredString("customBackgroundDescription");

    internal static string DebugActionFailureMessage => GetRequiredString("debugActionFailureMessage");

    internal static string DebugActionFailureTitle => GetRequiredString("debugActionFailureTitle");

    internal static string DebugActionToastMessage => GetRequiredString("debugActionToastMessage");

    internal static string DebugActionToastTitle => GetRequiredString("debugActionToastTitle");

    internal static string DebugCriticalErrorMessage => GetRequiredString("debugCriticalErrorMessage");

    internal static string DebugCriticalErrorTriggered => GetRequiredString("debugCriticalErrorTriggered");

    internal static string DebugExportCancelled => GetRequiredString("debugExportCancelled");

    internal static string DebugGameOperations => GetRequiredString("debugGameOperations");

    internal static string DebugHandledErrorMessage => GetRequiredString("debugHandledErrorMessage");

    internal static string DebugHandledErrorSimulated => GetRequiredString("debugHandledErrorSimulated");

    internal static string DebugIdle => GetRequiredString("debugIdle");

    internal static string DebugLogEntryWritten => GetRequiredString("debugLogEntryWritten");

    internal static string DebugLogExportUnavailable => GetRequiredString("debugLogExportUnavailable");

    internal static string DebugLogLevelSet => GetRequiredString("debugLogLevelSet");

    internal static string DebugOutput => GetRequiredString("debugOutput");

    internal static string DebugPanel => GetRequiredString("debugPanel");

    internal static string DebugPauseResume => GetRequiredString("debugPauseResume");

    internal static string DebugResetSettingsConfirm => GetRequiredString("debugResetSettingsConfirm");

    internal static string DebugResetSettingsDescription => GetRequiredString("debugResetSettingsDescription");

    internal static string DebugResetSettingsTitle => GetRequiredString("debugResetSettingsTitle");

    internal static string DebugSettingsReadFailed => GetRequiredString("debugSettingsReadFailed");

    internal static string DebugSettingsReset => GetRequiredString("debugSettingsReset");

    internal static string DebugSimulateError => GetRequiredString("debugSimulateError");

    internal static string DebugSimulateFailure => GetRequiredString("debugSimulateFailure");

    internal static string DebugSimulateSuccess => GetRequiredString("debugSimulateSuccess");

    internal static string DebugStateRefreshTriggered => GetRequiredString("debugStateRefreshTriggered");

    internal static string DebugStatus => GetRequiredString("debugStatus");

    internal static string DebugSystemInfo => GetRequiredString("debugSystemInfo");

    internal static string DebugSystemInfoFormat => GetRequiredString("debugSystemInfoFormat");

    internal static string DebugTestActionToast => GetRequiredString("debugTestActionToast");

    internal static string DebugTestErrorToast => GetRequiredString("debugTestErrorToast");

    internal static string DebugTestInfoToast => GetRequiredString("debugTestInfoToast");

    internal static string DebugTestLogMessage => GetRequiredString("debugTestLogMessage");

    internal static string DebugTestSuccessToast => GetRequiredString("debugTestSuccessToast");

    internal static string DebugTestToastMessage => GetRequiredString("debugTestToastMessage");

    internal static string DebugTestWarningToast => GetRequiredString("debugTestWarningToast");

    internal static string DebugToastShown => GetRequiredString("debugToastShown");

    internal static string DeletingManifestFiles => GetRequiredString("deletingManifestFiles");

    internal static string DesignGalleryHint => GetRequiredString("designGalleryHint");

    internal static string DesignGalleryTitle => GetRequiredString("designGalleryTitle");

    internal static string DesignGroupColor => GetRequiredString("designGroupColor");

    internal static string DesignGroupComponent => GetRequiredString("designGroupComponent");

    internal static string DesignGroupControl => GetRequiredString("designGroupControl");

    internal static string DesignGroupElevation => GetRequiredString("designGroupElevation");

    internal static string DesignGroupIcon => GetRequiredString("designGroupIcon");

    internal static string DesignGroupLayout => GetRequiredString("designGroupLayout");

    internal static string DesignGroupMotion => GetRequiredString("designGroupMotion");

    internal static string DesignGroupOther => GetRequiredString("designGroupOther");

    internal static string DesignGroupRadius => GetRequiredString("designGroupRadius");

    internal static string DesignGroupSpacing => GetRequiredString("designGroupSpacing");

    internal static string DesignGroupStateLayer => GetRequiredString("designGroupStateLayer");

    internal static string DesignGroupText => GetRequiredString("designGroupText");

    internal static string DesignGroupTypography => GetRequiredString("designGroupTypography");

    internal static string DesignMatrixCardWithToast => GetRequiredString("designMatrixCardWithToast");

    internal static string DesignMatrixErrorButton => GetRequiredString("designMatrixErrorButton");

    internal static string DesignMatrixFilledButton => GetRequiredString("designMatrixFilledButton");

    internal static string DesignMatrixOutlinedButton => GetRequiredString("designMatrixOutlinedButton");

    internal static string DesignMatrixSettingsRow => GetRequiredString("designMatrixSettingsRow");

    internal static string DesignMatrixTextButton => GetRequiredString("designMatrixTextButton");

    internal static string DesignStateDisabled => GetRequiredString("designStateDisabled");

    internal static string DesignStateFocus => GetRequiredString("designStateFocus");

    internal static string DesignStateHover => GetRequiredString("designStateHover");

    internal static string DesignStateInvalid => GetRequiredString("designStateInvalid");

    internal static string DesignStateNormal => GetRequiredString("designStateNormal");

    internal static string DesignStatePressed => GetRequiredString("designStatePressed");

    internal static string DiscardChanges => GetRequiredString("discardChanges");

    internal static string DiskSpace => GetRequiredString("diskSpace");

    internal static string DiskSpaceCheck => GetRequiredString("diskSpaceCheck");

    internal static string DiskSpaceEmpty => GetRequiredString("diskSpaceEmpty");

    internal static string DiskSpaceInsufficient => GetRequiredString("diskSpaceInsufficient");

    internal static string DiskSpaceInsufficientDetail => GetRequiredString("diskSpaceInsufficientDetail");

    internal static string DiskSpaceOkSuffix => GetRequiredString("diskSpaceOkSuffix");

    internal static string DiskSpaceShortSuffix => GetRequiredString("diskSpaceShortSuffix");

    internal static string Downloading => GetRequiredString("downloading");

    internal static string DownloadRemoteConfigIncomplete => GetRequiredString("downloadRemoteConfigIncomplete");

    internal static string DownloadSource => GetRequiredString("downloadSource");

    internal static string DownloadSourceCafe => GetRequiredString("downloadSourceCafe");

    internal static string DownloadSourceChangedRepairPrompt => GetRequiredString("downloadSourceChangedRepairPrompt");

    internal static string DownloadSourceDescription => GetRequiredString("downloadSourceDescription");

    internal static string DownloadSourceOfficial => GetRequiredString("downloadSourceOfficial");

    internal static string DownloadSpeedLimit => GetRequiredString("downloadSpeedLimit");

    internal static string DownloadSpeedLimitDescription => GetRequiredString("downloadSpeedLimitDescription");

    internal static string EnableStartupUpdateCheck => GetRequiredString("enableStartupUpdateCheck");

    internal static string EnableStartupUpdateCheckDescription => GetRequiredString("enableStartupUpdateCheckDescription");

    internal static string ErrorDialogContinue => GetRequiredString("errorDialogContinue");

    internal static string ErrorDialogCopyDetails => GetRequiredString("errorDialogCopyDetails");

    internal static string ErrorDialogDescription => GetRequiredString("errorDialogDescription");

    internal static string ErrorDialogTitle => GetRequiredString("errorDialogTitle");

    internal static string ErrorDialogViewLog => GetRequiredString("errorDialogViewLog");

    internal static string EstimatedTimeRemaining => GetRequiredString("estimatedTimeRemaining");

    internal static string Executable => GetRequiredString("executable");

    internal static string ExecutableLoading => GetRequiredString("executableLoading");

    internal static string ExecutableNameValue => GetRequiredString("executableNameValue");

    internal static string ExecutableValue => GetRequiredString("executableValue");

    internal static string ExitLauncher => GetRequiredString("exitLauncher");

    internal static string ExportLogs => GetRequiredString("exportLogs");

    internal static string FileOperationFailed => GetRequiredString("fileOperationFailed");

    internal static string FolderPickerUnavailable => GetRequiredString("folderPickerUnavailable");

    internal static string GameAlreadyCurrent => GetRequiredString("gameAlreadyCurrent");

    internal static string GameBelowLowestVersion => GetRequiredString("gameBelowLowestVersion");

    internal static string GameConfigMetadataMissing => GetRequiredString("gameConfigMetadataMissing");

    internal static string GameCorruptedInstallationState => GetRequiredString("gameCorruptedInstallationState");

    internal static string GameDirectoryNameInvalid => GetRequiredString("gameDirectoryNameInvalid");

    internal static string GameExecutableMissing => GetRequiredString("gameExecutableMissing");

    internal static string GameExecutableNameEmpty => GetRequiredString("gameExecutableNameEmpty");

    internal static string GameExecutableNameInvalid => GetRequiredString("gameExecutableNameInvalid");

    internal static string GameExecutableRunning => GetRequiredString("gameExecutableRunning");

    internal static string GameInstallationStateReadFailed => GetRequiredString("gameInstallationStateReadFailed");

    internal static string GameInstallPathNotConfigured => GetRequiredString("gameInstallPathNotConfigured");

    internal static string GameIsRunning => GetRequiredString("gameIsRunning");

    internal static string GameLaunchedMinimized => GetRequiredString("gameLaunchedMinimized");

    internal static string GameLaunchFailed => GetRequiredString("gameLaunchFailed");

    internal static string GameManagement => GetRequiredString("gameManagement");

    internal static string GameManagementDescription => GetRequiredString("gameManagementDescription");

    internal static string GameNotInstalled => GetRequiredString("gameNotInstalled");

    internal static string GamePath => GetRequiredString("gamePath");

    internal static string GamePathMissing => GetRequiredString("gamePathMissing");

    internal static string GamePathProtected => GetRequiredString("gamePathProtected");

    internal static string GamePathUpdated => GetRequiredString("gamePathUpdated");

    internal static string GamePathUpdateFailed => GetRequiredString("gamePathUpdateFailed");

    internal static string GameProcessStarted => GetRequiredString("gameProcessStarted");

    internal static string GameProcessStartFailed => GetRequiredString("gameProcessStartFailed");

    internal static string GameRemoteStateUnavailable => GetRequiredString("gameRemoteStateUnavailable");

    internal static string GitHubRepository => GetRequiredString("gitHubRepository");

    internal static string HelpDocs => GetRequiredString("helpDocs");

    internal static string InstallGame => GetRequiredString("installGame");

    internal static string InstallUpdateCompleted => GetRequiredString("installUpdateCompleted");

    internal static string InstallUpdateFailedTitle => GetRequiredString("installUpdateFailedTitle");

    internal static string KeepEditing => GetRequiredString("keepEditing");

    internal static string Language => GetRequiredString("language");

    internal static string LanguageAuto => GetRequiredString("languageAuto");

    internal static string LanguageDescription => GetRequiredString("languageDescription");

    internal static string LaunchCheck => GetRequiredString("launchCheck");

    internal static string LaunchCheckDescription => GetRequiredString("launchCheckDescription");

    internal static string LaunchCheckLoading => GetRequiredString("launchCheckLoading");

    internal static string LaunchCheckLocalManifest => GetRequiredString("launchCheckLocalManifest");

    internal static string LaunchCheckNone => GetRequiredString("launchCheckNone");

    internal static string LaunchCheckRemoteManifest => GetRequiredString("launchCheckRemoteManifest");

    internal static string LaunchCheckSkipped => GetRequiredString("launchCheckSkipped");

    internal static string LaunchCheckWithMessage => GetRequiredString("launchCheckWithMessage");

    internal static string LauncherLoadingStatus => GetRequiredString("launcherLoadingStatus");

    internal static string LauncherLoadingTitle => GetRequiredString("launcherLoadingTitle");

    internal static string LauncherLoadingValue => GetRequiredString("launcherLoadingValue");

    internal static string LauncherStateNotLoaded => GetRequiredString("launcherStateNotLoaded");

    internal static string LauncherUpdateAvailableMessage => GetRequiredString("launcherUpdateAvailableMessage");

    internal static string LauncherUpdateAvailableTitle => GetRequiredString("launcherUpdateAvailableTitle");

    internal static string LauncherUpdateChannel => GetRequiredString("launcherUpdateChannel");

    internal static string LauncherUpdateChannelBeta => GetRequiredString("launcherUpdateChannelBeta");

    internal static string LauncherUpdateChannelDescription => GetRequiredString("launcherUpdateChannelDescription");

    internal static string LauncherUpdateChannelStable => GetRequiredString("launcherUpdateChannelStable");

    internal static string LauncherUpdateCheckFailed => GetRequiredString("launcherUpdateCheckFailed");

    internal static string LauncherUpdateDownload => GetRequiredString("launcherUpdateDownload");

    internal static string LauncherUpdateFileSize => GetRequiredString("launcherUpdateFileSize");

    internal static string LauncherUpdateLater => GetRequiredString("launcherUpdateLater");

    internal static string LauncherUpdateSelectFile => GetRequiredString("launcherUpdateSelectFile");

    internal static string LauncherUpdateUpToDate => GetRequiredString("launcherUpdateUpToDate");

    internal static string LauncherVersionLabel => GetRequiredString("launcherVersionLabel");

    internal static string LocalGameReadError => GetRequiredString("localGameReadError");

    internal static string LocalManifestMetadataMissing => GetRequiredString("localManifestMetadataMissing");

    internal static string LocalManifestMissing => GetRequiredString("localManifestMissing");

    internal static string LocalManifestUnreadable => GetRequiredString("localManifestUnreadable");

    internal static string LogExportFailed => GetRequiredString("logExportFailed");

    internal static string LogExportFolderPickerTitle => GetRequiredString("logExportFolderPickerTitle");

    internal static string LogExportSucceeded => GetRequiredString("logExportSucceeded");

    internal static string LogFiles => GetRequiredString("logFiles");

    internal static string LogFilesDescription => GetRequiredString("logFilesDescription");

    internal static string LogFilterAll => GetRequiredString("logFilterAll");

    internal static string LogFilterDebug => GetRequiredString("logFilterDebug");

    internal static string LogFilterError => GetRequiredString("logFilterError");

    internal static string LogFilterFatal => GetRequiredString("logFilterFatal");

    internal static string LogFilterInfo => GetRequiredString("logFilterInfo");

    internal static string LogFilterVerbose => GetRequiredString("logFilterVerbose");

    internal static string LogFilterWarn => GetRequiredString("logFilterWarn");

    internal static string LogLevel => GetRequiredString("logLevel");

    internal static string LogLevelDebug => GetRequiredString("logLevelDebug");

    internal static string LogLevelDescription => GetRequiredString("logLevelDescription");

    internal static string LogLevelError => GetRequiredString("logLevelError");

    internal static string LogLevelFatal => GetRequiredString("logLevelFatal");

    internal static string LogLevelInformation => GetRequiredString("logLevelInformation");

    internal static string LogLevelVerbose => GetRequiredString("logLevelVerbose");

    internal static string LogLevelWarning => GetRequiredString("logLevelWarning");

    internal static string LogLoadEarlier => GetRequiredString("logLoadEarlier");

    internal static string LogNoMatchingEntries => GetRequiredString("logNoMatchingEntries");

    internal static string LogSearchPlaceholder => GetRequiredString("logSearchPlaceholder");

    internal static string LogViewerTitle => GetRequiredString("logViewerTitle");

    internal static string ManifestValidationFailed => GetRequiredString("manifestValidationFailed");

    internal static string ManifestValidationPassed => GetRequiredString("manifestValidationPassed");

    internal static string Minimize => GetRequiredString("minimize");

    internal static string MotionMode => GetRequiredString("motionMode");

    internal static string MotionModeDescription => GetRequiredString("motionModeDescription");

    internal static string MotionModeFull => GetRequiredString("motionModeFull");

    internal static string MotionModeReduced => GetRequiredString("motionModeReduced");

    internal static string MotionModeSystem => GetRequiredString("motionModeSystem");

    internal static string Network => GetRequiredString("network");

    internal static string NetworkError => GetRequiredString("networkError");

    internal static string NetworkErrorDetail => GetRequiredString("networkErrorDetail");

    internal static string NetworkLoading => GetRequiredString("networkLoading");

    internal static string NetworkUnavailableTitle => GetRequiredString("networkUnavailableTitle");

    internal static string NetworkWithMessage => GetRequiredString("networkWithMessage");

    internal static string NeutralColorStrategy => GetRequiredString("neutralColorStrategy");

    internal static string NeutralColorStrategyBrandBlue => GetRequiredString("neutralColorStrategyBrandBlue");

    internal static string NeutralColorStrategyDescription => GetRequiredString("neutralColorStrategyDescription");

    internal static string NeutralColorStrategySeedFollowing => GetRequiredString("neutralColorStrategySeedFollowing");

    internal static string NeutralColorStrategySeedFollowingHint => GetRequiredString("neutralColorStrategySeedFollowingHint");

    internal static string News => GetRequiredString("news");

    internal static string NextBanner => GetRequiredString("nextBanner");

    internal static string Notice => GetRequiredString("notice");

    internal static string NoticeConfirm => GetRequiredString("noticeConfirm");

    internal static string NoticeExit => GetRequiredString("noticeExit");

    internal static string OfficialSite => GetRequiredString("officialSite");

    internal static string OpenColorPalette => GetRequiredString("openColorPalette");

    internal static string OpenDataDirectory => GetRequiredString("openDataDirectory");

    internal static string OpenDesignGallery => GetRequiredString("openDesignGallery");

    internal static string OperationStopped => GetRequiredString("operationStopped");

    internal static string OperationTelemetryLocal => GetRequiredString("operationTelemetryLocal");

    internal static string OperationUnavailableForCurrentState => GetRequiredString("operationUnavailableForCurrentState");

    internal static string Path => GetRequiredString("path");

    internal static string PathLoading => GetRequiredString("pathLoading");

    internal static string Pause => GetRequiredString("pause");

    internal static string Paused => GetRequiredString("paused");

    internal static string PauseRequested => GetRequiredString("pauseRequested");

    internal static string PlatformLabel => GetRequiredString("platformLabel");

    internal static string Preparing => GetRequiredString("preparing");

    internal static string PreviousBanner => GetRequiredString("previousBanner");

    internal static string Proxy => GetRequiredString("proxy");

    internal static string ProxyAuto => GetRequiredString("proxyAuto");

    internal static string ProxyDescription => GetRequiredString("proxyDescription");

    internal static string ProxyDirect => GetRequiredString("proxyDirect");

    internal static string ProxySystem => GetRequiredString("proxySystem");

    internal static string Ready => GetRequiredString("ready");

    internal static string ReadyToUninstall => GetRequiredString("readyToUninstall");

    internal static string Refresh => GetRequiredString("refresh");

    internal static string RefreshThemeColorPalette => GetRequiredString("refreshThemeColorPalette");

    internal static string RefreshTooltip => GetRequiredString("refreshTooltip");

    internal static string RememberWindowPositionAndSize => GetRequiredString("rememberWindowPositionAndSize");

    internal static string RememberWindowPositionAndSizeDescription => GetRequiredString("rememberWindowPositionAndSizeDescription");

    internal static string RemoteContentCard => GetRequiredString("remoteContentCard");

    internal static string RemoteContentCardDescription => GetRequiredString("remoteContentCardDescription");

    internal static string RemoteContentLoadFailed => GetRequiredString("remoteContentLoadFailed");

    internal static string RemoteContentLoading => GetRequiredString("remoteContentLoading");

    internal static string Repair => GetRequiredString("repair");

    internal static string RepairCheckingFiles => GetRequiredString("repairCheckingFiles");

    internal static string RepairCompleted => GetRequiredString("repairCompleted");

    internal static string RepairConfirm => GetRequiredString("repairConfirm");

    internal static string RepairConfirmDescription => GetRequiredString("repairConfirmDescription");

    internal static string RepairFilesNeeded => GetRequiredString("repairFilesNeeded");

    internal static string Repairing => GetRequiredString("repairing");

    internal static string RepairNoChanges => GetRequiredString("repairNoChanges");

    internal static string RepairNoFilesNeeded => GetRequiredString("repairNoFilesNeeded");

    internal static string RepairWarning => GetRequiredString("repairWarning");

    internal static string ResourcePanel => GetRequiredString("resourcePanel");

    internal static string ResourcePanelCafeOnlyDescription => GetRequiredString("resourcePanelCafeOnlyDescription");

    internal static string ResourcePanelCafeOnlyMessage => GetRequiredString("resourcePanelCafeOnlyMessage");

    internal static string ResourcePanelCafeOnlySwitch => GetRequiredString("resourcePanelCafeOnlySwitch");

    internal static string ResourcePanelCafeOnlyTitle => GetRequiredString("resourcePanelCafeOnlyTitle");

    internal static string ResourcePanelChangeUid => GetRequiredString("resourcePanelChangeUid");

    internal static string ResourcePanelCurrentUid => GetRequiredString("resourcePanelCurrentUid");

    internal static string ResourcePanelDescription => GetRequiredString("resourcePanelDescription");

    internal static string ResourcePanelEditUid => GetRequiredString("resourcePanelEditUid");

    internal static string ResourcePanelFailed => GetRequiredString("resourcePanelFailed");

    internal static string ResourcePanelGameText => GetRequiredString("resourcePanelGameText");

    internal static string ResourcePanelLoadFailed => GetRequiredString("resourcePanelLoadFailed");

    internal static string ResourcePanelLoading => GetRequiredString("resourcePanelLoading");

    internal static string ResourcePanelLocalizedVersion => GetRequiredString("resourcePanelLocalizedVersion");

    internal static string ResourcePanelMainVoice => GetRequiredString("resourcePanelMainVoice");

    internal static string ResourcePanelManualUid => GetRequiredString("resourcePanelManualUid");

    internal static string ResourcePanelMedia => GetRequiredString("resourcePanelMedia");

    internal static string ResourcePanelOfficialVersion => GetRequiredString("resourcePanelOfficialVersion");

    internal static string ResourcePanelReady => GetRequiredString("resourcePanelReady");

    internal static string ResourcePanelRefresh => GetRequiredString("resourcePanelRefresh");

    internal static string ResourcePanelSave => GetRequiredString("resourcePanelSave");

    internal static string ResourcePanelSaved => GetRequiredString("resourcePanelSaved");

    internal static string ResourcePanelSaveFailed => GetRequiredString("resourcePanelSaveFailed");

    internal static string ResourcePanelSaveUid => GetRequiredString("resourcePanelSaveUid");

    internal static string ResourcePanelUid => GetRequiredString("resourcePanelUid");

    internal static string ResourcePanelUidEmpty => GetRequiredString("resourcePanelUidEmpty");

    internal static string ResourcePanelUidInvalidFormat => GetRequiredString("resourcePanelUidInvalidFormat");

    internal static string ResourcePanelUidMissing => GetRequiredString("resourcePanelUidMissing");

    internal static string ResourcePanelUidSaved => GetRequiredString("resourcePanelUidSaved");

    internal static string ResourcePanelUidSource => GetRequiredString("resourcePanelUidSource");

    internal static string ResourcePanelUidSourceAuto => GetRequiredString("resourcePanelUidSourceAuto");

    internal static string ResourcePanelUidSourceCustom => GetRequiredString("resourcePanelUidSourceCustom");

    internal static string ResourcePanelWaiting => GetRequiredString("resourcePanelWaiting");

    internal static string Resume => GetRequiredString("resume");

    internal static string ResumeRequested => GetRequiredString("resumeRequested");

    internal static string Retry => GetRequiredString("retry");

    internal static string RunningLaunchCheck => GetRequiredString("runningLaunchCheck");

    internal static string Save => GetRequiredString("save");

    internal static string SelectInstalledGame => GetRequiredString("selectInstalledGame");

    internal static string Settings => GetRequiredString("settings");

    internal static string SettingsCategoryAbout => GetRequiredString("settingsCategoryAbout");

    internal static string SettingsCategoryAboutDescription => GetRequiredString("settingsCategoryAboutDescription");

    internal static string SettingsCategoryAdvanced => GetRequiredString("settingsCategoryAdvanced");

    internal static string SettingsCategoryAdvancedDescription => GetRequiredString("settingsCategoryAdvancedDescription");

    internal static string SettingsCategoryAppearance => GetRequiredString("settingsCategoryAppearance");

    internal static string SettingsCategoryAppearanceDescription => GetRequiredString("settingsCategoryAppearanceDescription");

    internal static string SettingsCategoryDownloadNetwork => GetRequiredString("settingsCategoryDownloadNetwork");

    internal static string SettingsCategoryDownloadNetworkDescription => GetRequiredString("settingsCategoryDownloadNetworkDescription");

    internal static string SettingsCategoryGame => GetRequiredString("settingsCategoryGame");

    internal static string SettingsCategoryGameDescription => GetRequiredString("settingsCategoryGameDescription");

    internal static string SettingsCategoryGeneral => GetRequiredString("settingsCategoryGeneral");

    internal static string SettingsCategoryGeneralDescription => GetRequiredString("settingsCategoryGeneralDescription");

    internal static string SettingsCategoryNotificationsContent => GetRequiredString("settingsCategoryNotificationsContent");

    internal static string SettingsCategoryNotificationsContentDescription => GetRequiredString("settingsCategoryNotificationsContentDescription");

    internal static string SettingsGroupAboutActions => GetRequiredString("settingsGroupAboutActions");

    internal static string SettingsGroupAppPreferences => GetRequiredString("settingsGroupAppPreferences");

    internal static string SettingsGroupBackground => GetRequiredString("settingsGroupBackground");

    internal static string SettingsGroupConnection => GetRequiredString("settingsGroupConnection");

    internal static string SettingsGroupDiagnostics => GetRequiredString("settingsGroupDiagnostics");

    internal static string SettingsGroupDisplay => GetRequiredString("settingsGroupDisplay");

    internal static string SettingsGroupGameFiles => GetRequiredString("settingsGroupGameFiles");

    internal static string SettingsGroupThemeColor => GetRequiredString("settingsGroupThemeColor");

    internal static string SettingsSaved => GetRequiredString("settingsSaved");

    internal static string SettingsSaveFailed => GetRequiredString("settingsSaveFailed");

    internal static string SettingsSummaryWithTheme => GetRequiredString("settingsSummaryWithTheme");

    internal static string SetupWizardBrowse => GetRequiredString("setupWizardBrowse");

    internal static string SetupWizardDownloadSource => GetRequiredString("setupWizardDownloadSource");

    internal static string SetupWizardDownloadSourceCafeDescription => GetRequiredString("setupWizardDownloadSourceCafeDescription");

    internal static string SetupWizardDownloadSourceCafeRecommendationLabel => GetRequiredString("setupWizardDownloadSourceCafeRecommendationLabel");

    internal static string SetupWizardDownloadSourceCafeRecommendationReason => GetRequiredString("setupWizardDownloadSourceCafeRecommendationReason");

    internal static string SetupWizardDownloadSourceHint => GetRequiredString("setupWizardDownloadSourceHint");

    internal static string SetupWizardDownloadSourceOfficialDescription => GetRequiredString("setupWizardDownloadSourceOfficialDescription");

    internal static string SetupWizardEditStep => GetRequiredString("setupWizardEditStep");

    internal static string SetupWizardExitConfirm => GetRequiredString("setupWizardExitConfirm");

    internal static string SetupWizardExitMessage => GetRequiredString("setupWizardExitMessage");

    internal static string SetupWizardExitTitle => GetRequiredString("setupWizardExitTitle");

    internal static string SetupWizardFinish => GetRequiredString("setupWizardFinish");

    internal static string SetupWizardGamePath => GetRequiredString("setupWizardGamePath");

    internal static string SetupWizardGamePathAvailable => GetRequiredString("setupWizardGamePathAvailable");

    internal static string SetupWizardGamePathChecking => GetRequiredString("setupWizardGamePathChecking");

    internal static string SetupWizardGamePathCorrupted => GetRequiredString("setupWizardGamePathCorrupted");

    internal static string SetupWizardGamePathEmpty => GetRequiredString("setupWizardGamePathEmpty");

    internal static string SetupWizardGamePathHint => GetRequiredString("setupWizardGamePathHint");

    internal static string SetupWizardGamePathInaccessible => GetRequiredString("setupWizardGamePathInaccessible");

    internal static string SetupWizardGamePathInstalled => GetRequiredString("setupWizardGamePathInstalled");

    internal static string SetupWizardGamePathStatusDescription => GetRequiredString("setupWizardGamePathStatusDescription");

    internal static string SetupWizardGamePathStatusTitle => GetRequiredString("setupWizardGamePathStatusTitle");

    internal static string SetupWizardLanguage => GetRequiredString("setupWizardLanguage");

    internal static string SetupWizardLanguageHint => GetRequiredString("setupWizardLanguageHint");

    internal static string SetupWizardNext => GetRequiredString("setupWizardNext");

    internal static string SetupWizardPrevious => GetRequiredString("setupWizardPrevious");

    internal static string SetupWizardProxy => GetRequiredString("setupWizardProxy");

    internal static string SetupWizardProxyAutoDescription => GetRequiredString("setupWizardProxyAutoDescription");

    internal static string SetupWizardProxyDirectDescription => GetRequiredString("setupWizardProxyDirectDescription");

    internal static string SetupWizardProxyHint => GetRequiredString("setupWizardProxyHint");

    internal static string SetupWizardProxySystemDescription => GetRequiredString("setupWizardProxySystemDescription");

    internal static string SetupWizardReview => GetRequiredString("setupWizardReview");

    internal static string SetupWizardReviewHint => GetRequiredString("setupWizardReviewHint");

    internal static string SetupWizardSkip => GetRequiredString("setupWizardSkip");

    internal static string SetupWizardStep0Title => GetRequiredString("setupWizardStep0Title");

    internal static string SetupWizardStep1Title => GetRequiredString("setupWizardStep1Title");

    internal static string SetupWizardStep2Title => GetRequiredString("setupWizardStep2Title");

    internal static string SetupWizardStep3Title => GetRequiredString("setupWizardStep3Title");

    internal static string SetupWizardStep4Title => GetRequiredString("setupWizardStep4Title");

    internal static string SetupWizardStepTitle => GetRequiredString("setupWizardStepTitle");

    internal static string SetupWizardWelcomeText => GetRequiredString("setupWizardWelcomeText");

    internal static string SetupWizardWelcomeTitle => GetRequiredString("setupWizardWelcomeTitle");

    internal static string ShowLauncher => GetRequiredString("showLauncher");

    internal static string ShowRemoteContentCard => GetRequiredString("showRemoteContentCard");

    internal static string SocialMedia => GetRequiredString("socialMedia");

    internal static string Speed10MBs => GetRequiredString("speed10MBs");

    internal static string Speed1MBs => GetRequiredString("speed1MBs");

    internal static string Speed25MBs => GetRequiredString("speed25MBs");

    internal static string Speed50MBs => GetRequiredString("speed50MBs");

    internal static string Speed5MBs => GetRequiredString("speed5MBs");

    internal static string SpeedUnlimited => GetRequiredString("speedUnlimited");

    internal static string StartGame => GetRequiredString("startGame");

    internal static string StartupUpdateAvailable => GetRequiredString("startupUpdateAvailable");

    internal static string StatusDetailMode => GetRequiredString("statusDetailMode");

    internal static string StatusDetailModeCompact => GetRequiredString("statusDetailModeCompact");

    internal static string StatusDetailModeDescription => GetRequiredString("statusDetailModeDescription");

    internal static string StatusDetailModeHidden => GetRequiredString("statusDetailModeHidden");

    internal static string StatusLaunchCheckLocal => GetRequiredString("statusLaunchCheckLocal");

    internal static string StatusLaunchCheckNone => GetRequiredString("statusLaunchCheckNone");

    internal static string StatusLaunchCheckRemote => GetRequiredString("statusLaunchCheckRemote");

    internal static string StatusNetworkLoaded => GetRequiredString("statusNetworkLoaded");

    internal static string Stop => GetRequiredString("stop");

    internal static string StopDownloadMessage => GetRequiredString("stopDownloadMessage");

    internal static string StopDownloadTitle => GetRequiredString("stopDownloadTitle");

    internal static string StopRequested => GetRequiredString("stopRequested");

    internal static string Theme => GetRequiredString("theme");

    internal static string ThemeColor => GetRequiredString("themeColor");

    internal static string ThemeColorCustom => GetRequiredString("themeColorCustom");

    internal static string ThemeColorDefault => GetRequiredString("themeColorDefault");

    internal static string ThemeColorDescription => GetRequiredString("themeColorDescription");

    internal static string ThemeColorExtractionAlgorithm => GetRequiredString("themeColorExtractionAlgorithm");

    internal static string ThemeColorExtractionAlgorithmCelebiScore => GetRequiredString("themeColorExtractionAlgorithmCelebiScore");

    internal static string ThemeColorExtractionAlgorithmDescription => GetRequiredString("themeColorExtractionAlgorithmDescription");

    internal static string ThemeColorExtractionAlgorithmOctree => GetRequiredString("themeColorExtractionAlgorithmOctree");

    internal static string ThemeColorExtractionAlgorithmWsmeans => GetRequiredString("themeColorExtractionAlgorithmWsmeans");

    internal static string ThemeColorExtractionAlgorithmWu => GetRequiredString("themeColorExtractionAlgorithmWu");

    internal static string ThemeColorPalette => GetRequiredString("themeColorPalette");

    internal static string ThemeColorPaletteDescription => GetRequiredString("themeColorPaletteDescription");

    internal static string ThemeColorSystem => GetRequiredString("themeColorSystem");

    internal static string ThemeColorVariant => GetRequiredString("themeColorVariant");

    internal static string ThemeColorVariantContent => GetRequiredString("themeColorVariantContent");

    internal static string ThemeColorVariantDescription => GetRequiredString("themeColorVariantDescription");

    internal static string ThemeColorVariantExpressive => GetRequiredString("themeColorVariantExpressive");

    internal static string ThemeColorVariantFidelity => GetRequiredString("themeColorVariantFidelity");

    internal static string ThemeColorVariantMonochrome => GetRequiredString("themeColorVariantMonochrome");

    internal static string ThemeColorVariantNeutral => GetRequiredString("themeColorVariantNeutral");

    internal static string ThemeColorVariantRainbow => GetRequiredString("themeColorVariantRainbow");

    internal static string ThemeColorVariantTonalSpot => GetRequiredString("themeColorVariantTonalSpot");

    internal static string ThemeColorVariantVibrant => GetRequiredString("themeColorVariantVibrant");

    internal static string ThemeColorWallpaper => GetRequiredString("themeColorWallpaper");

    internal static string ThemeDark => GetRequiredString("themeDark");

    internal static string ThemeDescription => GetRequiredString("themeDescription");

    internal static string ThemeLight => GetRequiredString("themeLight");

    internal static string ThemeSystem => GetRequiredString("themeSystem");

    internal static string ToastActionFailedMessage => GetRequiredString("toastActionFailedMessage");

    internal static string ToastActionFailedTitle => GetRequiredString("toastActionFailedTitle");

    internal static string ToastError => GetRequiredString("toastError");

    internal static string ToastInfo => GetRequiredString("toastInfo");

    internal static string ToastSuccess => GetRequiredString("toastSuccess");

    internal static string ToastWarning => GetRequiredString("toastWarning");

    internal static string ToggleOff => GetRequiredString("toggleOff");

    internal static string ToggleOn => GetRequiredString("toggleOn");

    internal static string TrayExitLauncher => GetRequiredString("trayExitLauncher");

    internal static string TrayOpenLauncher => GetRequiredString("trayOpenLauncher");

    internal static string UnexpectedError => GetRequiredString("unexpectedError");

    internal static string Uninstall => GetRequiredString("uninstall");

    internal static string UninstallCompleted => GetRequiredString("uninstallCompleted");

    internal static string UninstallConfirmDescription => GetRequiredString("uninstallConfirmDescription");

    internal static string UninstallConfirmText => GetRequiredString("uninstallConfirmText");

    internal static string UninstallFailed => GetRequiredString("uninstallFailed");

    internal static string Uninstalling => GetRequiredString("uninstalling");

    internal static string Unknown => GetRequiredString("unknown");

    internal static string UnsavedChanges => GetRequiredString("unsavedChanges");

    internal static string UnsavedChangesMessage => GetRequiredString("unsavedChangesMessage");

    internal static string UpdateAvailable => GetRequiredString("updateAvailable");

    internal static string UpdateCheckingFiles => GetRequiredString("updateCheckingFiles");

    internal static string UpdateGame => GetRequiredString("updateGame");

    internal static string UpdateRequired => GetRequiredString("updateRequired");

    internal static string VerificationFailed => GetRequiredString("verificationFailed");

    internal static string VerificationRetry => GetRequiredString("verificationRetry");

    internal static string VerifyingDownloadedFiles => GetRequiredString("verifyingDownloadedFiles");

    internal static string Version => GetRequiredString("version");

    internal static string VersionInfo => GetRequiredString("versionInfo");

    internal static string VersionInstalled => GetRequiredString("versionInstalled");

    internal static string VersionLatest => GetRequiredString("versionLatest");

    internal static string VersionLoading => GetRequiredString("versionLoading");

    internal static string VersionUnavailable => GetRequiredString("versionUnavailable");

    internal static string ViewLog => GetRequiredString("viewLog");

    internal static string Working => GetRequiredString("working");
}
