# Requires -Version 7
<#
.SYNOPSIS
Regenerates src/Cafe.Launcher.Avalonia/Constants/LocalizationKeys.cs from the
neutral Resources/LauncherStrings.resx.

.DESCRIPTION
Every resource key becomes a `public const string` on the LocalizationKeys class
so C# call sites can reference keys without raw string literals (typos then fail
at compile time instead of silently rendering a key at runtime). Run this script
after adding or renaming a key in LauncherStrings.resx, then run
Test-LocalizationContract.ps1.

The generated file is committed to the repository; this script is the only
sanctioned way to change it.
#>

$ErrorActionPreference = 'Stop'

$resolvedRepoRoot = if ($PSScriptRoot) { Split-Path -Parent $PSScriptRoot } else { (Get-Location).Path }
$resxPath = Join-Path $resolvedRepoRoot 'src/Cafe.Launcher.Avalonia/Resources/LauncherStrings.resx'
$outputPath = Join-Path $resolvedRepoRoot 'src/Cafe.Launcher.Avalonia/Constants/LocalizationKeys.cs'

$resx = New-Object System.Xml.XmlDocument
$resx.Load($resxPath)
$keys = @($resx.root.data | Where-Object { $_.name } | ForEach-Object { $_.name } | Sort-Object -Unique)
if ($keys.Count -eq 0) {
    throw "No resource keys found in $resxPath."
}

$csharpKeywords = @('abstract','as','base','bool','break','byte','case','catch','char','checked','class','const',
    'continue','decimal','default','delegate','do','double','else','enum','event','explicit','extern',
    'false','finally','fixed','float','for','foreach','goto','if','implicit','in','int','interface',
    'internal','is','lock','long','namespace','new','null','object','operator','out','override',
    'params','private','protected','public','readonly','ref','return','sbyte','sealed','short','sizeof',
    'stackalloc','static','string','struct','switch','this','throw','true','try','typeof','uint','ulong',
    'unchecked','unsafe','ushort','using','var','virtual','void','volatile','while')

function ConvertTo-PascalIdentifier {
    param([string]$Key)

    $segments = $Key -split '[^A-Za-z0-9]+' | Where-Object { $_ }
    $identifier = ($segments | ForEach-Object {
        if ($_.Length -eq 1) { $_.ToUpperInvariant() }
        else { [char]::ToUpperInvariant($_[0]) + $_.Substring(1) }
    }) -join ''

    if ($identifier -notmatch '^[A-Za-z]') {
        $identifier = "Key$identifier"
    }

    if ($csharpKeywords -ccontains $identifier) {
        $identifier = "Key$identifier"
    }

    return $identifier
}

$names = @{}
$usedIdentifiers = @{}
foreach ($key in $keys) {
    $identifier = ConvertTo-PascalIdentifier -Key $key
    if ($usedIdentifiers.ContainsKey($identifier)) {
        throw "Identifier collision: '$key' maps to '$identifier', which is already used."
    }

    $usedIdentifiers[$identifier] = $true
    $names[$key] = $identifier
}

$entries = foreach ($key in $keys) {
    '    /// <summary>Resource key for <c>{0}</c>.</summary>' -f $key
    '    public const string {0} = "{1}";' -f $names[$key], $key
    ''
}

$header = @'
// <auto-generated>
//     Generated by scripts/Generate-LocalizationKeys.ps1 from
//     Resources/LauncherStrings.resx. Do not edit by hand; rerun the script
//     after adding or renaming a resource key.
// </auto-generated>

namespace Cafe.Launcher.Avalonia.Constants;

/// <summary>
/// Compile-time names for every LauncherStrings resource key. C# call sites must
/// reference these constants instead of raw string literals so a renamed or
/// misspelled key breaks the build rather than rendering a raw key at runtime.
/// </summary>
public static class LocalizationKeys
{
'@

$content = ($header + "`n" + ($entries -join "`n") + '}' + "`n") -replace "`r?`n", "`n"
$existing = if (Test-Path -LiteralPath $outputPath) { Get-Content -LiteralPath $outputPath -Raw } else { $null }
if ($existing -cne $content) {
    [System.IO.File]::WriteAllText($outputPath, $content, [System.Text.UTF8Encoding]::new($false))
    Write-Host "Wrote $outputPath ($($keys.Count) keys)."
}
else {
    Write-Host "LocalizationKeys.cs is up to date ($($keys.Count) keys)."
}
