param(
    [string]$ResourceFile = (Join-Path $PSScriptRoot '..\src\Cafe.Launcher.Avalonia\Resources\LauncherStrings.resx'),
    [string]$OutputFile = (Join-Path $PSScriptRoot '..\src\Cafe.Launcher.Avalonia\Resources\LauncherStrings.Designer.cs')
)

$ErrorActionPreference = 'Stop'

if (-not (Test-Path -LiteralPath $ResourceFile)) {
    throw "Neutral resource file was not found: $ResourceFile"
}

[xml]$resourceDocument = Get-Content -LiteralPath $ResourceFile -Raw -Encoding UTF8
$keys = @($resourceDocument.root.data | ForEach-Object { $_.name } | Sort-Object -CaseSensitive)

if ($keys.Count -eq 0) {
    throw "No resource keys were found in $ResourceFile"
}

$propertyNames = @{}
foreach ($key in $keys) {
    $propertyName = $key.Substring(0, 1).ToUpperInvariant() + $key.Substring(1)
    if ($propertyNames.ContainsKey($propertyName)) {
        throw "Resource keys '$($propertyNames[$propertyName])' and '$key' produce the same property name '$propertyName'."
    }

    $propertyNames[$propertyName] = $key
}

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('#nullable enable')
$lines.Add('')
$lines.Add('namespace Cafe.Launcher.Avalonia.Resources;')
$lines.Add('')
$lines.Add('using System.Globalization;')
$lines.Add('using System.Resources;')
$lines.Add('')
$lines.Add('/// <summary>')
$lines.Add('/// Strongly typed accessors for <c>LauncherStrings.resx</c>.')
$lines.Add('/// Generated by scripts/Generate-LauncherStringsDesigner.ps1; do not edit by hand.')
$lines.Add('/// </summary>')
$lines.Add('[System.CodeDom.Compiler.GeneratedCodeAttribute("scripts/Generate-LauncherStringsDesigner.ps1", "1.0.0.0")]')
$lines.Add('[System.Diagnostics.DebuggerNonUserCodeAttribute]')
$lines.Add('internal static class LauncherStrings')
$lines.Add('{')
$lines.Add('    private static ResourceManager? resourceMan;')
$lines.Add('')
$lines.Add('    internal static ResourceManager ResourceManager =>')
$lines.Add('        resourceMan ??= new ResourceManager(')
$lines.Add('            "Cafe.Launcher.Avalonia.Resources.LauncherStrings",')
$lines.Add('            typeof(LauncherStrings).Assembly);')
$lines.Add('')
$lines.Add('    private static string GetRequiredString(string key) =>')
$lines.Add('        ResourceManager.GetString(key, CultureInfo.CurrentUICulture)')
$lines.Add('        ?? throw new MissingManifestResourceException($"Resource key ''{key}'' was not found.");')

foreach ($propertyName in ($propertyNames.Keys | Sort-Object -CaseSensitive)) {
    $key = $propertyNames[$propertyName]
    $lines.Add('')
    $lines.Add("    internal static string $propertyName => GetRequiredString(`"$key`");")
}

$lines.Add('}')

[System.IO.File]::WriteAllLines(
    $OutputFile,
    $lines,
    [System.Text.UTF8Encoding]::new($false))

Write-Host "Generated $($keys.Count) strongly typed resource accessors in $OutputFile."
