name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    env:
      Project_Path: Cafe.Launcher.Avalonia.csproj
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      AVALONIA_TELEMETRY_OPTOUT: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Restore (Debug)
        run: dotnet restore $env:Project_Path

      - name: Build (Debug)
        run: dotnet build $env:Project_Path -c Debug --no-restore

      - name: Build (Release)
        run: dotnet build $env:Project_Path -c Release

      - name: Publish (Release)
        run: dotnet publish $env:Project_Path -c Release -o publish

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: Cafe.Launcher.Avalonia
          path: publish\
