name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 40

    defaults:
      run:
        shell: pwsh

    env:
      Project_Path: src/Cafe.Launcher.Avalonia/Cafe.Launcher.Avalonia.csproj
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_NOLOGO: 1
      AVALONIA_TELEMETRY_OPTOUT: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 1

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.0.x
          cache: true
          cache-dependency-path: '**/*.csproj'

      - name: Test
        run: .\test.ps1 -Configuration Debug

      - name: Coverage
        run: .\coverage.ps1

      - name: Upload test and coverage reports
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: test-and-coverage-reports
          retention-days: 14
          path: |
            TestResults/**/*.trx
            TestResults/Coverage/**/coverage.cobertura.xml

      - name: Restore (win-x64)
        run: dotnet restore $env:Project_Path -r win-x64

      - name: Publish (Release, win-x64)
        run: dotnet publish $env:Project_Path -c Release -r win-x64 -o publish --no-restore
